// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTest1Entity = "test1"

// Test1Entity mapped from table <test1>
type Test1Entity struct {
	ID       int64   `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Username string  `gorm:"column:username;type:varchar(255)" json:"username"`
	Version  Version `gorm:"column:version;type:int" json:"version"`
}

// TableName Test1Entity's table name
func (*Test1Entity) TableName() string {
	return TableNameTest1Entity
}
