port: 8000
mode: release
salt: abcdef
# 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: gin-admin-api
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  charset: utf8mb4
  loc: Asia/Shanghai
# Redis配置
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
jwt:
  signingKey: ${JWT_SIGNING_KEY}
  expireTime: 10080