port: 8000
salt: abcdef
# 数据库配置
datasource:
  driverName: mysql
  host: 118.195.245.106
  port: 3306
  database: gin-admin-api
  username: root
  password: Dance_box123!
  charset: utf8mb4
  loc: Asia/Shanghai
