version: "3"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    hostname: mysqlServiceHost
    network_mode: bridge
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./user_srv.sql:/docker-entrypoint-initdb.d/user_srv.sql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=user_srv

  golang:
    build: .
    restart: on-failure
    network_mode: bridge
    ports:
      - "9090:9090"
    links:
      - mysql
    volumes:
      - /home/gin-admin-api:/go


