// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-admin-api/initialize"
	"gin-admin-api/internal/api/account"
	"gin-admin-api/internal/api/auth"
	"gin-admin-api/internal/api/base"
	"gin-admin-api/internal/api/resources"
	"gin-admin-api/internal/api/role"
	"gin-admin-api/internal/router"
)

// Injectors from wire.go:

// InitApp Wire 入口函数，描述完整依赖图
// 执行 make wire 后自动生成 wire_gen.go，本文件不参与编译
func InitApp(envString2 string) (*initialize.App, error) {
	serverConfig, err := initialize.NewConfig(envString2)
	if err != nil {
		return nil, err
	}
	logger := initialize.NewLogger()
	db, err := initialize.NewDB(serverConfig)
	if err != nil {
		return nil, err
	}
	client, err := initialize.NewRedis(serverConfig)
	if err != nil {
		return nil, err
	}
	baseApi := base.NewBaseApi(logger, db, serverConfig, client)
	iAuth := auth.NewAuth(baseApi)
	iSysAccount := account.NewSysAccount(baseApi)
	iRole := role.NewRole(baseApi)
	iResources := resources.NewResources(baseApi)
	adminRouter := router.NewAdminRouter(iAuth, iSysAccount, iRole, iResources)
	engine := initialize.NewRouter(serverConfig, logger, adminRouter, client)
	app := initialize.NewApp(serverConfig, engine, logger)
	return app, nil
}
