// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newCasbinRuleEntity(db *gorm.DB, opts ...gen.DOOption) casbinRuleEntity {
	_casbinRuleEntity := casbinRuleEntity{}

	_casbinRuleEntity.casbinRuleEntityDo.UseDB(db, opts...)
	_casbinRuleEntity.casbinRuleEntityDo.UseModel(&model.CasbinRuleEntity{})

	tableName := _casbinRuleEntity.casbinRuleEntityDo.TableName()
	_casbinRuleEntity.ALL = field.NewAsterisk(tableName)
	_casbinRuleEntity.ID = field.NewInt64(tableName, "id")
	_casbinRuleEntity.Ptype = field.NewString(tableName, "ptype")
	_casbinRuleEntity.V0 = field.NewString(tableName, "v0")
	_casbinRuleEntity.V1 = field.NewString(tableName, "v1")
	_casbinRuleEntity.V2 = field.NewString(tableName, "v2")
	_casbinRuleEntity.V3 = field.NewString(tableName, "v3")
	_casbinRuleEntity.V4 = field.NewString(tableName, "v4")
	_casbinRuleEntity.V5 = field.NewString(tableName, "v5")

	_casbinRuleEntity.fillFieldMap()

	return _casbinRuleEntity
}

type casbinRuleEntity struct {
	casbinRuleEntityDo

	ALL   field.Asterisk
	ID    field.Int64
	Ptype field.String
	V0    field.String
	V1    field.String
	V2    field.String
	V3    field.String
	V4    field.String
	V5    field.String

	fieldMap map[string]field.Expr
}

func (c casbinRuleEntity) Table(newTableName string) *casbinRuleEntity {
	c.casbinRuleEntityDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c casbinRuleEntity) As(alias string) *casbinRuleEntity {
	c.casbinRuleEntityDo.DO = *(c.casbinRuleEntityDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *casbinRuleEntity) updateTableName(table string) *casbinRuleEntity {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.Ptype = field.NewString(table, "ptype")
	c.V0 = field.NewString(table, "v0")
	c.V1 = field.NewString(table, "v1")
	c.V2 = field.NewString(table, "v2")
	c.V3 = field.NewString(table, "v3")
	c.V4 = field.NewString(table, "v4")
	c.V5 = field.NewString(table, "v5")

	c.fillFieldMap()

	return c
}

func (c *casbinRuleEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *casbinRuleEntity) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["ptype"] = c.Ptype
	c.fieldMap["v0"] = c.V0
	c.fieldMap["v1"] = c.V1
	c.fieldMap["v2"] = c.V2
	c.fieldMap["v3"] = c.V3
	c.fieldMap["v4"] = c.V4
	c.fieldMap["v5"] = c.V5
}

func (c casbinRuleEntity) clone(db *gorm.DB) casbinRuleEntity {
	c.casbinRuleEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c casbinRuleEntity) replaceDB(db *gorm.DB) casbinRuleEntity {
	c.casbinRuleEntityDo.ReplaceDB(db)
	return c
}

type casbinRuleEntityDo struct{ gen.DO }

type ICasbinRuleEntityDo interface {
	gen.SubQuery
	Debug() ICasbinRuleEntityDo
	WithContext(ctx context.Context) ICasbinRuleEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICasbinRuleEntityDo
	WriteDB() ICasbinRuleEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICasbinRuleEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICasbinRuleEntityDo
	Not(conds ...gen.Condition) ICasbinRuleEntityDo
	Or(conds ...gen.Condition) ICasbinRuleEntityDo
	Select(conds ...field.Expr) ICasbinRuleEntityDo
	Where(conds ...gen.Condition) ICasbinRuleEntityDo
	Order(conds ...field.Expr) ICasbinRuleEntityDo
	Distinct(cols ...field.Expr) ICasbinRuleEntityDo
	Omit(cols ...field.Expr) ICasbinRuleEntityDo
	Join(table schema.Tabler, on ...field.Expr) ICasbinRuleEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICasbinRuleEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICasbinRuleEntityDo
	Group(cols ...field.Expr) ICasbinRuleEntityDo
	Having(conds ...gen.Condition) ICasbinRuleEntityDo
	Limit(limit int) ICasbinRuleEntityDo
	Offset(offset int) ICasbinRuleEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICasbinRuleEntityDo
	Unscoped() ICasbinRuleEntityDo
	Create(values ...*model.CasbinRuleEntity) error
	CreateInBatches(values []*model.CasbinRuleEntity, batchSize int) error
	Save(values ...*model.CasbinRuleEntity) error
	First() (*model.CasbinRuleEntity, error)
	Take() (*model.CasbinRuleEntity, error)
	Last() (*model.CasbinRuleEntity, error)
	Find() ([]*model.CasbinRuleEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CasbinRuleEntity, err error)
	FindInBatches(result *[]*model.CasbinRuleEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CasbinRuleEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICasbinRuleEntityDo
	Assign(attrs ...field.AssignExpr) ICasbinRuleEntityDo
	Joins(fields ...field.RelationField) ICasbinRuleEntityDo
	Preload(fields ...field.RelationField) ICasbinRuleEntityDo
	FirstOrInit() (*model.CasbinRuleEntity, error)
	FirstOrCreate() (*model.CasbinRuleEntity, error)
	FindByPage(offset int, limit int) (result []*model.CasbinRuleEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICasbinRuleEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c casbinRuleEntityDo) Debug() ICasbinRuleEntityDo {
	return c.withDO(c.DO.Debug())
}

func (c casbinRuleEntityDo) WithContext(ctx context.Context) ICasbinRuleEntityDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c casbinRuleEntityDo) ReadDB() ICasbinRuleEntityDo {
	return c.Clauses(dbresolver.Read)
}

func (c casbinRuleEntityDo) WriteDB() ICasbinRuleEntityDo {
	return c.Clauses(dbresolver.Write)
}

func (c casbinRuleEntityDo) Session(config *gorm.Session) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Session(config))
}

func (c casbinRuleEntityDo) Clauses(conds ...clause.Expression) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c casbinRuleEntityDo) Returning(value interface{}, columns ...string) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c casbinRuleEntityDo) Not(conds ...gen.Condition) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c casbinRuleEntityDo) Or(conds ...gen.Condition) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c casbinRuleEntityDo) Select(conds ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c casbinRuleEntityDo) Where(conds ...gen.Condition) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c casbinRuleEntityDo) Order(conds ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c casbinRuleEntityDo) Distinct(cols ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c casbinRuleEntityDo) Omit(cols ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c casbinRuleEntityDo) Join(table schema.Tabler, on ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c casbinRuleEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c casbinRuleEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c casbinRuleEntityDo) Group(cols ...field.Expr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c casbinRuleEntityDo) Having(conds ...gen.Condition) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c casbinRuleEntityDo) Limit(limit int) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c casbinRuleEntityDo) Offset(offset int) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c casbinRuleEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c casbinRuleEntityDo) Unscoped() ICasbinRuleEntityDo {
	return c.withDO(c.DO.Unscoped())
}

func (c casbinRuleEntityDo) Create(values ...*model.CasbinRuleEntity) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c casbinRuleEntityDo) CreateInBatches(values []*model.CasbinRuleEntity, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c casbinRuleEntityDo) Save(values ...*model.CasbinRuleEntity) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c casbinRuleEntityDo) First() (*model.CasbinRuleEntity, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CasbinRuleEntity), nil
	}
}

func (c casbinRuleEntityDo) Take() (*model.CasbinRuleEntity, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CasbinRuleEntity), nil
	}
}

func (c casbinRuleEntityDo) Last() (*model.CasbinRuleEntity, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CasbinRuleEntity), nil
	}
}

func (c casbinRuleEntityDo) Find() ([]*model.CasbinRuleEntity, error) {
	result, err := c.DO.Find()
	return result.([]*model.CasbinRuleEntity), err
}

func (c casbinRuleEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CasbinRuleEntity, err error) {
	buf := make([]*model.CasbinRuleEntity, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c casbinRuleEntityDo) FindInBatches(result *[]*model.CasbinRuleEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c casbinRuleEntityDo) Attrs(attrs ...field.AssignExpr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c casbinRuleEntityDo) Assign(attrs ...field.AssignExpr) ICasbinRuleEntityDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c casbinRuleEntityDo) Joins(fields ...field.RelationField) ICasbinRuleEntityDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c casbinRuleEntityDo) Preload(fields ...field.RelationField) ICasbinRuleEntityDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c casbinRuleEntityDo) FirstOrInit() (*model.CasbinRuleEntity, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CasbinRuleEntity), nil
	}
}

func (c casbinRuleEntityDo) FirstOrCreate() (*model.CasbinRuleEntity, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CasbinRuleEntity), nil
	}
}

func (c casbinRuleEntityDo) FindByPage(offset int, limit int) (result []*model.CasbinRuleEntity, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c casbinRuleEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c casbinRuleEntityDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c casbinRuleEntityDo) Delete(models ...*model.CasbinRuleEntity) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *casbinRuleEntityDo) withDO(do gen.Dao) *casbinRuleEntityDo {
	c.DO = *do.(*gen.DO)
	return c
}
