// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	SysAccountEntity       *sysAccountEntity
	SysAccountRoleEntity   *sysAccountRoleEntity
	SysResourcesEntity     *sysResourcesEntity
	SysRoleEntity          *sysRoleEntity
	SysRoleResourcesEntity *sysRoleResourcesEntity
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SysAccountEntity = &Q.SysAccountEntity
	SysAccountRoleEntity = &Q.SysAccountRoleEntity
	SysResourcesEntity = &Q.SysResourcesEntity
	SysRoleEntity = &Q.SysRoleEntity
	SysRoleResourcesEntity = &Q.SysRoleResourcesEntity
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		SysAccountEntity:       newSysAccountEntity(db, opts...),
		SysAccountRoleEntity:   newSysAccountRoleEntity(db, opts...),
		SysResourcesEntity:     newSysResourcesEntity(db, opts...),
		SysRoleEntity:          newSysRoleEntity(db, opts...),
		SysRoleResourcesEntity: newSysRoleResourcesEntity(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SysAccountEntity       sysAccountEntity
	SysAccountRoleEntity   sysAccountRoleEntity
	SysResourcesEntity     sysResourcesEntity
	SysRoleEntity          sysRoleEntity
	SysRoleResourcesEntity sysRoleResourcesEntity
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		SysAccountEntity:       q.SysAccountEntity.clone(db),
		SysAccountRoleEntity:   q.SysAccountRoleEntity.clone(db),
		SysResourcesEntity:     q.SysResourcesEntity.clone(db),
		SysRoleEntity:          q.SysRoleEntity.clone(db),
		SysRoleResourcesEntity: q.SysRoleResourcesEntity.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		SysAccountEntity:       q.SysAccountEntity.replaceDB(db),
		SysAccountRoleEntity:   q.SysAccountRoleEntity.replaceDB(db),
		SysResourcesEntity:     q.SysResourcesEntity.replaceDB(db),
		SysRoleEntity:          q.SysRoleEntity.replaceDB(db),
		SysRoleResourcesEntity: q.SysRoleResourcesEntity.replaceDB(db),
	}
}

type queryCtx struct {
	SysAccountEntity       ISysAccountEntityDo
	SysAccountRoleEntity   ISysAccountRoleEntityDo
	SysResourcesEntity     ISysResourcesEntityDo
	SysRoleEntity          ISysRoleEntityDo
	SysRoleResourcesEntity ISysRoleResourcesEntityDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SysAccountEntity:       q.SysAccountEntity.WithContext(ctx),
		SysAccountRoleEntity:   q.SysAccountRoleEntity.WithContext(ctx),
		SysResourcesEntity:     q.SysResourcesEntity.WithContext(ctx),
		SysRoleEntity:          q.SysRoleEntity.WithContext(ctx),
		SysRoleResourcesEntity: q.SysRoleResourcesEntity.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
