// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                       = new(Query)
	CasbinRuleEntity        *casbinRuleEntity
	SysAccountEntity        *sysAccountEntity
	SysAccountPostEntity    *sysAccountPostEntity
	SysAccountRoleEntity    *sysAccountRoleEntity
	SysDeptEntity           *sysDeptEntity
	SysPostEntity           *sysPostEntity
	SysResourcesEntity      *sysResourcesEntity
	SysRoleCustomDeptEntity *sysRoleCustomDeptEntity
	SysRoleEntity           *sysRoleEntity
	SysRoleResourcesEntity  *sysRoleResourcesEntity
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CasbinRuleEntity = &Q.CasbinRuleEntity
	SysAccountEntity = &Q.SysAccountEntity
	SysAccountPostEntity = &Q.SysAccountPostEntity
	SysAccountRoleEntity = &Q.SysAccountRoleEntity
	SysDeptEntity = &Q.SysDeptEntity
	SysPostEntity = &Q.SysPostEntity
	SysResourcesEntity = &Q.SysResourcesEntity
	SysRoleCustomDeptEntity = &Q.SysRoleCustomDeptEntity
	SysRoleEntity = &Q.SysRoleEntity
	SysRoleResourcesEntity = &Q.SysRoleResourcesEntity
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                      db,
		CasbinRuleEntity:        newCasbinRuleEntity(db, opts...),
		SysAccountEntity:        newSysAccountEntity(db, opts...),
		SysAccountPostEntity:    newSysAccountPostEntity(db, opts...),
		SysAccountRoleEntity:    newSysAccountRoleEntity(db, opts...),
		SysDeptEntity:           newSysDeptEntity(db, opts...),
		SysPostEntity:           newSysPostEntity(db, opts...),
		SysResourcesEntity:      newSysResourcesEntity(db, opts...),
		SysRoleCustomDeptEntity: newSysRoleCustomDeptEntity(db, opts...),
		SysRoleEntity:           newSysRoleEntity(db, opts...),
		SysRoleResourcesEntity:  newSysRoleResourcesEntity(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CasbinRuleEntity        casbinRuleEntity
	SysAccountEntity        sysAccountEntity
	SysAccountPostEntity    sysAccountPostEntity
	SysAccountRoleEntity    sysAccountRoleEntity
	SysDeptEntity           sysDeptEntity
	SysPostEntity           sysPostEntity
	SysResourcesEntity      sysResourcesEntity
	SysRoleCustomDeptEntity sysRoleCustomDeptEntity
	SysRoleEntity           sysRoleEntity
	SysRoleResourcesEntity  sysRoleResourcesEntity
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		CasbinRuleEntity:        q.CasbinRuleEntity.clone(db),
		SysAccountEntity:        q.SysAccountEntity.clone(db),
		SysAccountPostEntity:    q.SysAccountPostEntity.clone(db),
		SysAccountRoleEntity:    q.SysAccountRoleEntity.clone(db),
		SysDeptEntity:           q.SysDeptEntity.clone(db),
		SysPostEntity:           q.SysPostEntity.clone(db),
		SysResourcesEntity:      q.SysResourcesEntity.clone(db),
		SysRoleCustomDeptEntity: q.SysRoleCustomDeptEntity.clone(db),
		SysRoleEntity:           q.SysRoleEntity.clone(db),
		SysRoleResourcesEntity:  q.SysRoleResourcesEntity.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                      db,
		CasbinRuleEntity:        q.CasbinRuleEntity.replaceDB(db),
		SysAccountEntity:        q.SysAccountEntity.replaceDB(db),
		SysAccountPostEntity:    q.SysAccountPostEntity.replaceDB(db),
		SysAccountRoleEntity:    q.SysAccountRoleEntity.replaceDB(db),
		SysDeptEntity:           q.SysDeptEntity.replaceDB(db),
		SysPostEntity:           q.SysPostEntity.replaceDB(db),
		SysResourcesEntity:      q.SysResourcesEntity.replaceDB(db),
		SysRoleCustomDeptEntity: q.SysRoleCustomDeptEntity.replaceDB(db),
		SysRoleEntity:           q.SysRoleEntity.replaceDB(db),
		SysRoleResourcesEntity:  q.SysRoleResourcesEntity.replaceDB(db),
	}
}

type queryCtx struct {
	CasbinRuleEntity        ICasbinRuleEntityDo
	SysAccountEntity        ISysAccountEntityDo
	SysAccountPostEntity    ISysAccountPostEntityDo
	SysAccountRoleEntity    ISysAccountRoleEntityDo
	SysDeptEntity           ISysDeptEntityDo
	SysPostEntity           ISysPostEntityDo
	SysResourcesEntity      ISysResourcesEntityDo
	SysRoleCustomDeptEntity ISysRoleCustomDeptEntityDo
	SysRoleEntity           ISysRoleEntityDo
	SysRoleResourcesEntity  ISysRoleResourcesEntityDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CasbinRuleEntity:        q.CasbinRuleEntity.WithContext(ctx),
		SysAccountEntity:        q.SysAccountEntity.WithContext(ctx),
		SysAccountPostEntity:    q.SysAccountPostEntity.WithContext(ctx),
		SysAccountRoleEntity:    q.SysAccountRoleEntity.WithContext(ctx),
		SysDeptEntity:           q.SysDeptEntity.WithContext(ctx),
		SysPostEntity:           q.SysPostEntity.WithContext(ctx),
		SysResourcesEntity:      q.SysResourcesEntity.WithContext(ctx),
		SysRoleCustomDeptEntity: q.SysRoleCustomDeptEntity.WithContext(ctx),
		SysRoleEntity:           q.SysRoleEntity.WithContext(ctx),
		SysRoleResourcesEntity:  q.SysRoleResourcesEntity.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
