// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysAccountEntity(db *gorm.DB, opts ...gen.DOOption) sysAccountEntity {
	_sysAccountEntity := sysAccountEntity{}

	_sysAccountEntity.sysAccountEntityDo.UseDB(db, opts...)
	_sysAccountEntity.sysAccountEntityDo.UseModel(&model.SysAccountEntity{})

	tableName := _sysAccountEntity.sysAccountEntityDo.TableName()
	_sysAccountEntity.ALL = field.NewAsterisk(tableName)
	_sysAccountEntity.ID = field.NewInt64(tableName, "id")
	_sysAccountEntity.Username = field.NewString(tableName, "username")
	_sysAccountEntity.Email = field.NewString(tableName, "email")
	_sysAccountEntity.Mobile = field.NewString(tableName, "mobile")
	_sysAccountEntity.Password = field.NewString(tableName, "password")
	_sysAccountEntity.LastLoginDate = field.NewTime(tableName, "last_login_date")
	_sysAccountEntity.LastLoginIP = field.NewString(tableName, "last_login_ip")
	_sysAccountEntity.Status = field.NewInt64(tableName, "status")
	_sysAccountEntity.Avatar = field.NewString(tableName, "avatar")
	_sysAccountEntity.IsAdmin = field.NewInt64(tableName, "is_admin")
	_sysAccountEntity.DeptID = field.NewInt64(tableName, "dept_id")
	_sysAccountEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysAccountEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysAccountEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysAccountEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysAccountEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysAccountEntity.fillFieldMap()

	return _sysAccountEntity
}

// sysAccountEntity 后台账号表
type sysAccountEntity struct {
	sysAccountEntityDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键id
	Username      field.String // 登录帐号
	Email         field.String // 邮箱
	Mobile        field.String // 手机号
	Password      field.String // 登录密码
	LastLoginDate field.Time   // 最后一次登录时间
	LastLoginIP   field.String // 最后一次登录ip
	Status        field.Int64  // 状态1是正常,2是禁用
	Avatar        field.String // 头像
	IsAdmin       field.Int64  // 1是超级管理员，2是普通管理员
	DeptID        field.Int64  // 所属部门id，用于数据权限计算
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 软删除时间
	CreatedBy     field.Int64  // 创建人
	UpdatedBy     field.Int64  // 更新人

	fieldMap map[string]field.Expr
}

func (s sysAccountEntity) Table(newTableName string) *sysAccountEntity {
	s.sysAccountEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAccountEntity) As(alias string) *sysAccountEntity {
	s.sysAccountEntityDo.DO = *(s.sysAccountEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAccountEntity) updateTableName(table string) *sysAccountEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Username = field.NewString(table, "username")
	s.Email = field.NewString(table, "email")
	s.Mobile = field.NewString(table, "mobile")
	s.Password = field.NewString(table, "password")
	s.LastLoginDate = field.NewTime(table, "last_login_date")
	s.LastLoginIP = field.NewString(table, "last_login_ip")
	s.Status = field.NewInt64(table, "status")
	s.Avatar = field.NewString(table, "avatar")
	s.IsAdmin = field.NewInt64(table, "is_admin")
	s.DeptID = field.NewInt64(table, "dept_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysAccountEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAccountEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["username"] = s.Username
	s.fieldMap["email"] = s.Email
	s.fieldMap["mobile"] = s.Mobile
	s.fieldMap["password"] = s.Password
	s.fieldMap["last_login_date"] = s.LastLoginDate
	s.fieldMap["last_login_ip"] = s.LastLoginIP
	s.fieldMap["status"] = s.Status
	s.fieldMap["avatar"] = s.Avatar
	s.fieldMap["is_admin"] = s.IsAdmin
	s.fieldMap["dept_id"] = s.DeptID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysAccountEntity) clone(db *gorm.DB) sysAccountEntity {
	s.sysAccountEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAccountEntity) replaceDB(db *gorm.DB) sysAccountEntity {
	s.sysAccountEntityDo.ReplaceDB(db)
	return s
}

type sysAccountEntityDo struct{ gen.DO }

type ISysAccountEntityDo interface {
	gen.SubQuery
	Debug() ISysAccountEntityDo
	WithContext(ctx context.Context) ISysAccountEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAccountEntityDo
	WriteDB() ISysAccountEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAccountEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAccountEntityDo
	Not(conds ...gen.Condition) ISysAccountEntityDo
	Or(conds ...gen.Condition) ISysAccountEntityDo
	Select(conds ...field.Expr) ISysAccountEntityDo
	Where(conds ...gen.Condition) ISysAccountEntityDo
	Order(conds ...field.Expr) ISysAccountEntityDo
	Distinct(cols ...field.Expr) ISysAccountEntityDo
	Omit(cols ...field.Expr) ISysAccountEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysAccountEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAccountEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAccountEntityDo
	Group(cols ...field.Expr) ISysAccountEntityDo
	Having(conds ...gen.Condition) ISysAccountEntityDo
	Limit(limit int) ISysAccountEntityDo
	Offset(offset int) ISysAccountEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAccountEntityDo
	Unscoped() ISysAccountEntityDo
	Create(values ...*model.SysAccountEntity) error
	CreateInBatches(values []*model.SysAccountEntity, batchSize int) error
	Save(values ...*model.SysAccountEntity) error
	First() (*model.SysAccountEntity, error)
	Take() (*model.SysAccountEntity, error)
	Last() (*model.SysAccountEntity, error)
	Find() ([]*model.SysAccountEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccountEntity, err error)
	FindInBatches(result *[]*model.SysAccountEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysAccountEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAccountEntityDo
	Assign(attrs ...field.AssignExpr) ISysAccountEntityDo
	Joins(fields ...field.RelationField) ISysAccountEntityDo
	Preload(fields ...field.RelationField) ISysAccountEntityDo
	FirstOrInit() (*model.SysAccountEntity, error)
	FirstOrCreate() (*model.SysAccountEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysAccountEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAccountEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAccountEntityDo) Debug() ISysAccountEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAccountEntityDo) WithContext(ctx context.Context) ISysAccountEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAccountEntityDo) ReadDB() ISysAccountEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAccountEntityDo) WriteDB() ISysAccountEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAccountEntityDo) Session(config *gorm.Session) ISysAccountEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAccountEntityDo) Clauses(conds ...clause.Expression) ISysAccountEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAccountEntityDo) Returning(value interface{}, columns ...string) ISysAccountEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAccountEntityDo) Not(conds ...gen.Condition) ISysAccountEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAccountEntityDo) Or(conds ...gen.Condition) ISysAccountEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAccountEntityDo) Select(conds ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAccountEntityDo) Where(conds ...gen.Condition) ISysAccountEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAccountEntityDo) Order(conds ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAccountEntityDo) Distinct(cols ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAccountEntityDo) Omit(cols ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAccountEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAccountEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAccountEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAccountEntityDo) Group(cols ...field.Expr) ISysAccountEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAccountEntityDo) Having(conds ...gen.Condition) ISysAccountEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAccountEntityDo) Limit(limit int) ISysAccountEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAccountEntityDo) Offset(offset int) ISysAccountEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAccountEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAccountEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAccountEntityDo) Unscoped() ISysAccountEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAccountEntityDo) Create(values ...*model.SysAccountEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAccountEntityDo) CreateInBatches(values []*model.SysAccountEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAccountEntityDo) Save(values ...*model.SysAccountEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAccountEntityDo) First() (*model.SysAccountEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountEntity), nil
	}
}

func (s sysAccountEntityDo) Take() (*model.SysAccountEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountEntity), nil
	}
}

func (s sysAccountEntityDo) Last() (*model.SysAccountEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountEntity), nil
	}
}

func (s sysAccountEntityDo) Find() ([]*model.SysAccountEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysAccountEntity), err
}

func (s sysAccountEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccountEntity, err error) {
	buf := make([]*model.SysAccountEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAccountEntityDo) FindInBatches(result *[]*model.SysAccountEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAccountEntityDo) Attrs(attrs ...field.AssignExpr) ISysAccountEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAccountEntityDo) Assign(attrs ...field.AssignExpr) ISysAccountEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAccountEntityDo) Joins(fields ...field.RelationField) ISysAccountEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAccountEntityDo) Preload(fields ...field.RelationField) ISysAccountEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAccountEntityDo) FirstOrInit() (*model.SysAccountEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountEntity), nil
	}
}

func (s sysAccountEntityDo) FirstOrCreate() (*model.SysAccountEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountEntity), nil
	}
}

func (s sysAccountEntityDo) FindByPage(offset int, limit int) (result []*model.SysAccountEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAccountEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAccountEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAccountEntityDo) Delete(models ...*model.SysAccountEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAccountEntityDo) withDO(do gen.Dao) *sysAccountEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
