// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysRoleEntity(db *gorm.DB, opts ...gen.DOOption) sysRoleEntity {
	_sysRoleEntity := sysRoleEntity{}

	_sysRoleEntity.sysRoleEntityDo.UseDB(db, opts...)
	_sysRoleEntity.sysRoleEntityDo.UseModel(&model.SysRoleEntity{})

	tableName := _sysRoleEntity.sysRoleEntityDo.TableName()
	_sysRoleEntity.ALL = field.NewAsterisk(tableName)
	_sysRoleEntity.ID = field.NewInt64(tableName, "id")
	_sysRoleEntity.Name = field.NewString(tableName, "name")
	_sysRoleEntity.Description = field.NewString(tableName, "description")
	_sysRoleEntity.Status = field.NewInt64(tableName, "status")
	_sysRoleEntity.Sort = field.NewInt64(tableName, "sort")
	_sysRoleEntity.DataScope = field.NewInt64(tableName, "data_scope")
	_sysRoleEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRoleEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRoleEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysRoleEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysRoleEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysRoleEntity.fillFieldMap()

	return _sysRoleEntity
}

// sysRoleEntity 角色表
type sysRoleEntity struct {
	sysRoleEntityDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键id
	Name        field.String // 角色名称
	Description field.String // 描述
	Status      field.Int64  // 状态1是正常,2是禁用
	Sort        field.Int64  // 排序
	DataScope   field.Int64  // 数据范围：1=全部 2=本部门 3=本部门及下级 4=仅本人 5=自定义部门
	CreatedAt   field.Time   // 创建时间
	UpdatedAt   field.Time   // 更新时间
	DeletedAt   field.Field  // 软删除时间
	CreatedBy   field.Int64  // 创建人
	UpdatedBy   field.Int64  // 更新人

	fieldMap map[string]field.Expr
}

func (s sysRoleEntity) Table(newTableName string) *sysRoleEntity {
	s.sysRoleEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRoleEntity) As(alias string) *sysRoleEntity {
	s.sysRoleEntityDo.DO = *(s.sysRoleEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRoleEntity) updateTableName(table string) *sysRoleEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Description = field.NewString(table, "description")
	s.Status = field.NewInt64(table, "status")
	s.Sort = field.NewInt64(table, "sort")
	s.DataScope = field.NewInt64(table, "data_scope")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysRoleEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRoleEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["description"] = s.Description
	s.fieldMap["status"] = s.Status
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["data_scope"] = s.DataScope
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysRoleEntity) clone(db *gorm.DB) sysRoleEntity {
	s.sysRoleEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRoleEntity) replaceDB(db *gorm.DB) sysRoleEntity {
	s.sysRoleEntityDo.ReplaceDB(db)
	return s
}

type sysRoleEntityDo struct{ gen.DO }

type ISysRoleEntityDo interface {
	gen.SubQuery
	Debug() ISysRoleEntityDo
	WithContext(ctx context.Context) ISysRoleEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleEntityDo
	WriteDB() ISysRoleEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleEntityDo
	Not(conds ...gen.Condition) ISysRoleEntityDo
	Or(conds ...gen.Condition) ISysRoleEntityDo
	Select(conds ...field.Expr) ISysRoleEntityDo
	Where(conds ...gen.Condition) ISysRoleEntityDo
	Order(conds ...field.Expr) ISysRoleEntityDo
	Distinct(cols ...field.Expr) ISysRoleEntityDo
	Omit(cols ...field.Expr) ISysRoleEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleEntityDo
	Group(cols ...field.Expr) ISysRoleEntityDo
	Having(conds ...gen.Condition) ISysRoleEntityDo
	Limit(limit int) ISysRoleEntityDo
	Offset(offset int) ISysRoleEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleEntityDo
	Unscoped() ISysRoleEntityDo
	Create(values ...*model.SysRoleEntity) error
	CreateInBatches(values []*model.SysRoleEntity, batchSize int) error
	Save(values ...*model.SysRoleEntity) error
	First() (*model.SysRoleEntity, error)
	Take() (*model.SysRoleEntity, error)
	Last() (*model.SysRoleEntity, error)
	Find() ([]*model.SysRoleEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleEntity, err error)
	FindInBatches(result *[]*model.SysRoleEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRoleEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleEntityDo
	Assign(attrs ...field.AssignExpr) ISysRoleEntityDo
	Joins(fields ...field.RelationField) ISysRoleEntityDo
	Preload(fields ...field.RelationField) ISysRoleEntityDo
	FirstOrInit() (*model.SysRoleEntity, error)
	FirstOrCreate() (*model.SysRoleEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysRoleEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleEntityDo) Debug() ISysRoleEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleEntityDo) WithContext(ctx context.Context) ISysRoleEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleEntityDo) ReadDB() ISysRoleEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleEntityDo) WriteDB() ISysRoleEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleEntityDo) Session(config *gorm.Session) ISysRoleEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleEntityDo) Clauses(conds ...clause.Expression) ISysRoleEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleEntityDo) Returning(value interface{}, columns ...string) ISysRoleEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleEntityDo) Not(conds ...gen.Condition) ISysRoleEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleEntityDo) Or(conds ...gen.Condition) ISysRoleEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleEntityDo) Select(conds ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleEntityDo) Where(conds ...gen.Condition) ISysRoleEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleEntityDo) Order(conds ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleEntityDo) Distinct(cols ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleEntityDo) Omit(cols ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleEntityDo) Group(cols ...field.Expr) ISysRoleEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleEntityDo) Having(conds ...gen.Condition) ISysRoleEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleEntityDo) Limit(limit int) ISysRoleEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleEntityDo) Offset(offset int) ISysRoleEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleEntityDo) Unscoped() ISysRoleEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleEntityDo) Create(values ...*model.SysRoleEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleEntityDo) CreateInBatches(values []*model.SysRoleEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleEntityDo) Save(values ...*model.SysRoleEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleEntityDo) First() (*model.SysRoleEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleEntity), nil
	}
}

func (s sysRoleEntityDo) Take() (*model.SysRoleEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleEntity), nil
	}
}

func (s sysRoleEntityDo) Last() (*model.SysRoleEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleEntity), nil
	}
}

func (s sysRoleEntityDo) Find() ([]*model.SysRoleEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRoleEntity), err
}

func (s sysRoleEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleEntity, err error) {
	buf := make([]*model.SysRoleEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleEntityDo) FindInBatches(result *[]*model.SysRoleEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleEntityDo) Attrs(attrs ...field.AssignExpr) ISysRoleEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleEntityDo) Assign(attrs ...field.AssignExpr) ISysRoleEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleEntityDo) Joins(fields ...field.RelationField) ISysRoleEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleEntityDo) Preload(fields ...field.RelationField) ISysRoleEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleEntityDo) FirstOrInit() (*model.SysRoleEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleEntity), nil
	}
}

func (s sysRoleEntityDo) FirstOrCreate() (*model.SysRoleEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleEntity), nil
	}
}

func (s sysRoleEntityDo) FindByPage(offset int, limit int) (result []*model.SysRoleEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleEntityDo) Delete(models ...*model.SysRoleEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleEntityDo) withDO(do gen.Dao) *sysRoleEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
