// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysDeptEntity(db *gorm.DB, opts ...gen.DOOption) sysDeptEntity {
	_sysDeptEntity := sysDeptEntity{}

	_sysDeptEntity.sysDeptEntityDo.UseDB(db, opts...)
	_sysDeptEntity.sysDeptEntityDo.UseModel(&model.SysDeptEntity{})

	tableName := _sysDeptEntity.sysDeptEntityDo.TableName()
	_sysDeptEntity.ALL = field.NewAsterisk(tableName)
	_sysDeptEntity.ID = field.NewInt64(tableName, "id")
	_sysDeptEntity.Name = field.NewString(tableName, "name")
	_sysDeptEntity.ParentID = field.NewInt64(tableName, "parent_id")
	_sysDeptEntity.FullID = field.NewString(tableName, "full_id")
	_sysDeptEntity.FullName = field.NewString(tableName, "full_name")
	_sysDeptEntity.Sort = field.NewInt64(tableName, "sort")
	_sysDeptEntity.Status = field.NewInt64(tableName, "status")
	_sysDeptEntity.Leader = field.NewString(tableName, "leader")
	_sysDeptEntity.Phone = field.NewString(tableName, "phone")
	_sysDeptEntity.Email = field.NewString(tableName, "email")
	_sysDeptEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysDeptEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysDeptEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysDeptEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysDeptEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysDeptEntity.fillFieldMap()

	return _sysDeptEntity
}

// sysDeptEntity 部门表
type sysDeptEntity struct {
	sysDeptEntityDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键id
	Name      field.String // 部门名称
	ParentID  field.Int64  // 上级部门id
	FullID    field.String // 全层级ID，例：1,5,12
	FullName  field.String // 全层级名称
	Sort      field.Int64  // 排序
	Status    field.Int64  // 状态1正常 2禁用
	Leader    field.String // 负责人
	Phone     field.String // 联系电话
	Email     field.String // 邮箱
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 软删除时间
	CreatedBy field.Int64  // 创建人
	UpdatedBy field.Int64  // 更新人

	fieldMap map[string]field.Expr
}

func (s sysDeptEntity) Table(newTableName string) *sysDeptEntity {
	s.sysDeptEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDeptEntity) As(alias string) *sysDeptEntity {
	s.sysDeptEntityDo.DO = *(s.sysDeptEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDeptEntity) updateTableName(table string) *sysDeptEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.ParentID = field.NewInt64(table, "parent_id")
	s.FullID = field.NewString(table, "full_id")
	s.FullName = field.NewString(table, "full_name")
	s.Sort = field.NewInt64(table, "sort")
	s.Status = field.NewInt64(table, "status")
	s.Leader = field.NewString(table, "leader")
	s.Phone = field.NewString(table, "phone")
	s.Email = field.NewString(table, "email")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysDeptEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDeptEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["full_id"] = s.FullID
	s.fieldMap["full_name"] = s.FullName
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
	s.fieldMap["leader"] = s.Leader
	s.fieldMap["phone"] = s.Phone
	s.fieldMap["email"] = s.Email
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysDeptEntity) clone(db *gorm.DB) sysDeptEntity {
	s.sysDeptEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDeptEntity) replaceDB(db *gorm.DB) sysDeptEntity {
	s.sysDeptEntityDo.ReplaceDB(db)
	return s
}

type sysDeptEntityDo struct{ gen.DO }

type ISysDeptEntityDo interface {
	gen.SubQuery
	Debug() ISysDeptEntityDo
	WithContext(ctx context.Context) ISysDeptEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDeptEntityDo
	WriteDB() ISysDeptEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDeptEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDeptEntityDo
	Not(conds ...gen.Condition) ISysDeptEntityDo
	Or(conds ...gen.Condition) ISysDeptEntityDo
	Select(conds ...field.Expr) ISysDeptEntityDo
	Where(conds ...gen.Condition) ISysDeptEntityDo
	Order(conds ...field.Expr) ISysDeptEntityDo
	Distinct(cols ...field.Expr) ISysDeptEntityDo
	Omit(cols ...field.Expr) ISysDeptEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysDeptEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDeptEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDeptEntityDo
	Group(cols ...field.Expr) ISysDeptEntityDo
	Having(conds ...gen.Condition) ISysDeptEntityDo
	Limit(limit int) ISysDeptEntityDo
	Offset(offset int) ISysDeptEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDeptEntityDo
	Unscoped() ISysDeptEntityDo
	Create(values ...*model.SysDeptEntity) error
	CreateInBatches(values []*model.SysDeptEntity, batchSize int) error
	Save(values ...*model.SysDeptEntity) error
	First() (*model.SysDeptEntity, error)
	Take() (*model.SysDeptEntity, error)
	Last() (*model.SysDeptEntity, error)
	Find() ([]*model.SysDeptEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDeptEntity, err error)
	FindInBatches(result *[]*model.SysDeptEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysDeptEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDeptEntityDo
	Assign(attrs ...field.AssignExpr) ISysDeptEntityDo
	Joins(fields ...field.RelationField) ISysDeptEntityDo
	Preload(fields ...field.RelationField) ISysDeptEntityDo
	FirstOrInit() (*model.SysDeptEntity, error)
	FirstOrCreate() (*model.SysDeptEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysDeptEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDeptEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDeptEntityDo) Debug() ISysDeptEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDeptEntityDo) WithContext(ctx context.Context) ISysDeptEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDeptEntityDo) ReadDB() ISysDeptEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDeptEntityDo) WriteDB() ISysDeptEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDeptEntityDo) Session(config *gorm.Session) ISysDeptEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDeptEntityDo) Clauses(conds ...clause.Expression) ISysDeptEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDeptEntityDo) Returning(value interface{}, columns ...string) ISysDeptEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDeptEntityDo) Not(conds ...gen.Condition) ISysDeptEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDeptEntityDo) Or(conds ...gen.Condition) ISysDeptEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDeptEntityDo) Select(conds ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDeptEntityDo) Where(conds ...gen.Condition) ISysDeptEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDeptEntityDo) Order(conds ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDeptEntityDo) Distinct(cols ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDeptEntityDo) Omit(cols ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDeptEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDeptEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDeptEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDeptEntityDo) Group(cols ...field.Expr) ISysDeptEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDeptEntityDo) Having(conds ...gen.Condition) ISysDeptEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDeptEntityDo) Limit(limit int) ISysDeptEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDeptEntityDo) Offset(offset int) ISysDeptEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDeptEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDeptEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDeptEntityDo) Unscoped() ISysDeptEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDeptEntityDo) Create(values ...*model.SysDeptEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDeptEntityDo) CreateInBatches(values []*model.SysDeptEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDeptEntityDo) Save(values ...*model.SysDeptEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDeptEntityDo) First() (*model.SysDeptEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptEntity), nil
	}
}

func (s sysDeptEntityDo) Take() (*model.SysDeptEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptEntity), nil
	}
}

func (s sysDeptEntityDo) Last() (*model.SysDeptEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptEntity), nil
	}
}

func (s sysDeptEntityDo) Find() ([]*model.SysDeptEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysDeptEntity), err
}

func (s sysDeptEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDeptEntity, err error) {
	buf := make([]*model.SysDeptEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDeptEntityDo) FindInBatches(result *[]*model.SysDeptEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDeptEntityDo) Attrs(attrs ...field.AssignExpr) ISysDeptEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDeptEntityDo) Assign(attrs ...field.AssignExpr) ISysDeptEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDeptEntityDo) Joins(fields ...field.RelationField) ISysDeptEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDeptEntityDo) Preload(fields ...field.RelationField) ISysDeptEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDeptEntityDo) FirstOrInit() (*model.SysDeptEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptEntity), nil
	}
}

func (s sysDeptEntityDo) FirstOrCreate() (*model.SysDeptEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDeptEntity), nil
	}
}

func (s sysDeptEntityDo) FindByPage(offset int, limit int) (result []*model.SysDeptEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDeptEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDeptEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDeptEntityDo) Delete(models ...*model.SysDeptEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDeptEntityDo) withDO(do gen.Dao) *sysDeptEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
