// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysResourcesEntity(db *gorm.DB, opts ...gen.DOOption) sysResourcesEntity {
	_sysResourcesEntity := sysResourcesEntity{}

	_sysResourcesEntity.sysResourcesEntityDo.UseDB(db, opts...)
	_sysResourcesEntity.sysResourcesEntityDo.UseModel(&model.SysResourcesEntity{})

	tableName := _sysResourcesEntity.sysResourcesEntityDo.TableName()
	_sysResourcesEntity.ALL = field.NewAsterisk(tableName)
	_sysResourcesEntity.ID = field.NewInt64(tableName, "id")
	_sysResourcesEntity.Title = field.NewString(tableName, "title")
	_sysResourcesEntity.URL = field.NewString(tableName, "url")
	_sysResourcesEntity.Method = field.NewString(tableName, "method")
	_sysResourcesEntity.Icon = field.NewString(tableName, "icon")
	_sysResourcesEntity.ResourcesType = field.NewInt64(tableName, "resources_type")
	_sysResourcesEntity.IsCache = field.NewInt64(tableName, "is_cache")
	_sysResourcesEntity.IsHidden = field.NewInt64(tableName, "is_hidden")
	_sysResourcesEntity.IsLink = field.NewInt64(tableName, "is_link")
	_sysResourcesEntity.ParentID = field.NewInt64(tableName, "parent_id")
	_sysResourcesEntity.Sort = field.NewInt64(tableName, "sort")
	_sysResourcesEntity.Status = field.NewInt64(tableName, "status")
	_sysResourcesEntity.Description = field.NewString(tableName, "description")
	_sysResourcesEntity.IsAdminHave = field.NewInt64(tableName, "is_admin_have")
	_sysResourcesEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysResourcesEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysResourcesEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysResourcesEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysResourcesEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysResourcesEntity.fillFieldMap()

	return _sysResourcesEntity
}

// sysResourcesEntity 资源表
type sysResourcesEntity struct {
	sysResourcesEntityDo

	ALL           field.Asterisk
	ID            field.Int64  // 主键id
	Title         field.String // 名称:按钮标题,或菜单标题
	URL           field.String // 按钮请求url,或菜单路由
	Method        field.String // 接口的请求方式
	Icon          field.String // 菜单小图标
	ResourcesType field.Int64  // 类型:1表示目录,2表示菜单,3表示接口
	IsCache       field.Int64  // 是否缓存:1表示缓存:2不缓存
	IsHidden      field.Int64  // 是否隐藏:1表示不隐藏,2表示隐藏
	IsLink        field.Int64  // 是否为外部链接:1表示不是,2表示是
	ParentID      field.Int64  // 上一级id，0=顶级
	Sort          field.Int64  // 菜单,或按钮排序
	Status        field.Int64  // 状态1是正常,2是禁用
	Description   field.String // 描述
	IsAdminHave   field.Int64  // 是否超管独有,1表示是,0表示不是
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 软删除时间
	CreatedBy     field.Int64  // 创建人
	UpdatedBy     field.Int64  // 更新人

	fieldMap map[string]field.Expr
}

func (s sysResourcesEntity) Table(newTableName string) *sysResourcesEntity {
	s.sysResourcesEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysResourcesEntity) As(alias string) *sysResourcesEntity {
	s.sysResourcesEntityDo.DO = *(s.sysResourcesEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysResourcesEntity) updateTableName(table string) *sysResourcesEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Title = field.NewString(table, "title")
	s.URL = field.NewString(table, "url")
	s.Method = field.NewString(table, "method")
	s.Icon = field.NewString(table, "icon")
	s.ResourcesType = field.NewInt64(table, "resources_type")
	s.IsCache = field.NewInt64(table, "is_cache")
	s.IsHidden = field.NewInt64(table, "is_hidden")
	s.IsLink = field.NewInt64(table, "is_link")
	s.ParentID = field.NewInt64(table, "parent_id")
	s.Sort = field.NewInt64(table, "sort")
	s.Status = field.NewInt64(table, "status")
	s.Description = field.NewString(table, "description")
	s.IsAdminHave = field.NewInt64(table, "is_admin_have")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysResourcesEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysResourcesEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 19)
	s.fieldMap["id"] = s.ID
	s.fieldMap["title"] = s.Title
	s.fieldMap["url"] = s.URL
	s.fieldMap["method"] = s.Method
	s.fieldMap["icon"] = s.Icon
	s.fieldMap["resources_type"] = s.ResourcesType
	s.fieldMap["is_cache"] = s.IsCache
	s.fieldMap["is_hidden"] = s.IsHidden
	s.fieldMap["is_link"] = s.IsLink
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
	s.fieldMap["description"] = s.Description
	s.fieldMap["is_admin_have"] = s.IsAdminHave
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysResourcesEntity) clone(db *gorm.DB) sysResourcesEntity {
	s.sysResourcesEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysResourcesEntity) replaceDB(db *gorm.DB) sysResourcesEntity {
	s.sysResourcesEntityDo.ReplaceDB(db)
	return s
}

type sysResourcesEntityDo struct{ gen.DO }

type ISysResourcesEntityDo interface {
	gen.SubQuery
	Debug() ISysResourcesEntityDo
	WithContext(ctx context.Context) ISysResourcesEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysResourcesEntityDo
	WriteDB() ISysResourcesEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysResourcesEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysResourcesEntityDo
	Not(conds ...gen.Condition) ISysResourcesEntityDo
	Or(conds ...gen.Condition) ISysResourcesEntityDo
	Select(conds ...field.Expr) ISysResourcesEntityDo
	Where(conds ...gen.Condition) ISysResourcesEntityDo
	Order(conds ...field.Expr) ISysResourcesEntityDo
	Distinct(cols ...field.Expr) ISysResourcesEntityDo
	Omit(cols ...field.Expr) ISysResourcesEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysResourcesEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourcesEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysResourcesEntityDo
	Group(cols ...field.Expr) ISysResourcesEntityDo
	Having(conds ...gen.Condition) ISysResourcesEntityDo
	Limit(limit int) ISysResourcesEntityDo
	Offset(offset int) ISysResourcesEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourcesEntityDo
	Unscoped() ISysResourcesEntityDo
	Create(values ...*model.SysResourcesEntity) error
	CreateInBatches(values []*model.SysResourcesEntity, batchSize int) error
	Save(values ...*model.SysResourcesEntity) error
	First() (*model.SysResourcesEntity, error)
	Take() (*model.SysResourcesEntity, error)
	Last() (*model.SysResourcesEntity, error)
	Find() ([]*model.SysResourcesEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysResourcesEntity, err error)
	FindInBatches(result *[]*model.SysResourcesEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysResourcesEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysResourcesEntityDo
	Assign(attrs ...field.AssignExpr) ISysResourcesEntityDo
	Joins(fields ...field.RelationField) ISysResourcesEntityDo
	Preload(fields ...field.RelationField) ISysResourcesEntityDo
	FirstOrInit() (*model.SysResourcesEntity, error)
	FirstOrCreate() (*model.SysResourcesEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysResourcesEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysResourcesEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysResourcesEntityDo) Debug() ISysResourcesEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysResourcesEntityDo) WithContext(ctx context.Context) ISysResourcesEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysResourcesEntityDo) ReadDB() ISysResourcesEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysResourcesEntityDo) WriteDB() ISysResourcesEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysResourcesEntityDo) Session(config *gorm.Session) ISysResourcesEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysResourcesEntityDo) Clauses(conds ...clause.Expression) ISysResourcesEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysResourcesEntityDo) Returning(value interface{}, columns ...string) ISysResourcesEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysResourcesEntityDo) Not(conds ...gen.Condition) ISysResourcesEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysResourcesEntityDo) Or(conds ...gen.Condition) ISysResourcesEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysResourcesEntityDo) Select(conds ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysResourcesEntityDo) Where(conds ...gen.Condition) ISysResourcesEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysResourcesEntityDo) Order(conds ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysResourcesEntityDo) Distinct(cols ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysResourcesEntityDo) Omit(cols ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysResourcesEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysResourcesEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysResourcesEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysResourcesEntityDo) Group(cols ...field.Expr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysResourcesEntityDo) Having(conds ...gen.Condition) ISysResourcesEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysResourcesEntityDo) Limit(limit int) ISysResourcesEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysResourcesEntityDo) Offset(offset int) ISysResourcesEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysResourcesEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysResourcesEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysResourcesEntityDo) Unscoped() ISysResourcesEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysResourcesEntityDo) Create(values ...*model.SysResourcesEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysResourcesEntityDo) CreateInBatches(values []*model.SysResourcesEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysResourcesEntityDo) Save(values ...*model.SysResourcesEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysResourcesEntityDo) First() (*model.SysResourcesEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysResourcesEntity), nil
	}
}

func (s sysResourcesEntityDo) Take() (*model.SysResourcesEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysResourcesEntity), nil
	}
}

func (s sysResourcesEntityDo) Last() (*model.SysResourcesEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysResourcesEntity), nil
	}
}

func (s sysResourcesEntityDo) Find() ([]*model.SysResourcesEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysResourcesEntity), err
}

func (s sysResourcesEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysResourcesEntity, err error) {
	buf := make([]*model.SysResourcesEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysResourcesEntityDo) FindInBatches(result *[]*model.SysResourcesEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysResourcesEntityDo) Attrs(attrs ...field.AssignExpr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysResourcesEntityDo) Assign(attrs ...field.AssignExpr) ISysResourcesEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysResourcesEntityDo) Joins(fields ...field.RelationField) ISysResourcesEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysResourcesEntityDo) Preload(fields ...field.RelationField) ISysResourcesEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysResourcesEntityDo) FirstOrInit() (*model.SysResourcesEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysResourcesEntity), nil
	}
}

func (s sysResourcesEntityDo) FirstOrCreate() (*model.SysResourcesEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysResourcesEntity), nil
	}
}

func (s sysResourcesEntityDo) FindByPage(offset int, limit int) (result []*model.SysResourcesEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysResourcesEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysResourcesEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysResourcesEntityDo) Delete(models ...*model.SysResourcesEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysResourcesEntityDo) withDO(do gen.Dao) *sysResourcesEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
