// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysRoleCustomDeptEntity(db *gorm.DB, opts ...gen.DOOption) sysRoleCustomDeptEntity {
	_sysRoleCustomDeptEntity := sysRoleCustomDeptEntity{}

	_sysRoleCustomDeptEntity.sysRoleCustomDeptEntityDo.UseDB(db, opts...)
	_sysRoleCustomDeptEntity.sysRoleCustomDeptEntityDo.UseModel(&model.SysRoleCustomDeptEntity{})

	tableName := _sysRoleCustomDeptEntity.sysRoleCustomDeptEntityDo.TableName()
	_sysRoleCustomDeptEntity.ALL = field.NewAsterisk(tableName)
	_sysRoleCustomDeptEntity.ID = field.NewInt64(tableName, "id")
	_sysRoleCustomDeptEntity.RoleID = field.NewInt64(tableName, "role_id")
	_sysRoleCustomDeptEntity.DeptID = field.NewInt64(tableName, "dept_id")
	_sysRoleCustomDeptEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRoleCustomDeptEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRoleCustomDeptEntity.DeletedAt = field.NewField(tableName, "deleted_at")

	_sysRoleCustomDeptEntity.fillFieldMap()

	return _sysRoleCustomDeptEntity
}

// sysRoleCustomDeptEntity 角色自定义数据权限部门表
type sysRoleCustomDeptEntity struct {
	sysRoleCustomDeptEntityDo

	ALL       field.Asterisk
	ID        field.Int64 // 主键id
	RoleID    field.Int64 // 角色id
	DeptID    field.Int64 // 可查看部门id
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Time  // 更新时间
	DeletedAt field.Field // 软删除时间

	fieldMap map[string]field.Expr
}

func (s sysRoleCustomDeptEntity) Table(newTableName string) *sysRoleCustomDeptEntity {
	s.sysRoleCustomDeptEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRoleCustomDeptEntity) As(alias string) *sysRoleCustomDeptEntity {
	s.sysRoleCustomDeptEntityDo.DO = *(s.sysRoleCustomDeptEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRoleCustomDeptEntity) updateTableName(table string) *sysRoleCustomDeptEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.RoleID = field.NewInt64(table, "role_id")
	s.DeptID = field.NewInt64(table, "dept_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysRoleCustomDeptEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRoleCustomDeptEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 6)
	s.fieldMap["id"] = s.ID
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["dept_id"] = s.DeptID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sysRoleCustomDeptEntity) clone(db *gorm.DB) sysRoleCustomDeptEntity {
	s.sysRoleCustomDeptEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRoleCustomDeptEntity) replaceDB(db *gorm.DB) sysRoleCustomDeptEntity {
	s.sysRoleCustomDeptEntityDo.ReplaceDB(db)
	return s
}

type sysRoleCustomDeptEntityDo struct{ gen.DO }

type ISysRoleCustomDeptEntityDo interface {
	gen.SubQuery
	Debug() ISysRoleCustomDeptEntityDo
	WithContext(ctx context.Context) ISysRoleCustomDeptEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleCustomDeptEntityDo
	WriteDB() ISysRoleCustomDeptEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleCustomDeptEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleCustomDeptEntityDo
	Not(conds ...gen.Condition) ISysRoleCustomDeptEntityDo
	Or(conds ...gen.Condition) ISysRoleCustomDeptEntityDo
	Select(conds ...field.Expr) ISysRoleCustomDeptEntityDo
	Where(conds ...gen.Condition) ISysRoleCustomDeptEntityDo
	Order(conds ...field.Expr) ISysRoleCustomDeptEntityDo
	Distinct(cols ...field.Expr) ISysRoleCustomDeptEntityDo
	Omit(cols ...field.Expr) ISysRoleCustomDeptEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleCustomDeptEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleCustomDeptEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleCustomDeptEntityDo
	Group(cols ...field.Expr) ISysRoleCustomDeptEntityDo
	Having(conds ...gen.Condition) ISysRoleCustomDeptEntityDo
	Limit(limit int) ISysRoleCustomDeptEntityDo
	Offset(offset int) ISysRoleCustomDeptEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleCustomDeptEntityDo
	Unscoped() ISysRoleCustomDeptEntityDo
	Create(values ...*model.SysRoleCustomDeptEntity) error
	CreateInBatches(values []*model.SysRoleCustomDeptEntity, batchSize int) error
	Save(values ...*model.SysRoleCustomDeptEntity) error
	First() (*model.SysRoleCustomDeptEntity, error)
	Take() (*model.SysRoleCustomDeptEntity, error)
	Last() (*model.SysRoleCustomDeptEntity, error)
	Find() ([]*model.SysRoleCustomDeptEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleCustomDeptEntity, err error)
	FindInBatches(result *[]*model.SysRoleCustomDeptEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRoleCustomDeptEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleCustomDeptEntityDo
	Assign(attrs ...field.AssignExpr) ISysRoleCustomDeptEntityDo
	Joins(fields ...field.RelationField) ISysRoleCustomDeptEntityDo
	Preload(fields ...field.RelationField) ISysRoleCustomDeptEntityDo
	FirstOrInit() (*model.SysRoleCustomDeptEntity, error)
	FirstOrCreate() (*model.SysRoleCustomDeptEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysRoleCustomDeptEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleCustomDeptEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleCustomDeptEntityDo) Debug() ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleCustomDeptEntityDo) WithContext(ctx context.Context) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleCustomDeptEntityDo) ReadDB() ISysRoleCustomDeptEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleCustomDeptEntityDo) WriteDB() ISysRoleCustomDeptEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleCustomDeptEntityDo) Session(config *gorm.Session) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleCustomDeptEntityDo) Clauses(conds ...clause.Expression) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleCustomDeptEntityDo) Returning(value interface{}, columns ...string) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleCustomDeptEntityDo) Not(conds ...gen.Condition) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleCustomDeptEntityDo) Or(conds ...gen.Condition) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleCustomDeptEntityDo) Select(conds ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleCustomDeptEntityDo) Where(conds ...gen.Condition) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleCustomDeptEntityDo) Order(conds ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleCustomDeptEntityDo) Distinct(cols ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleCustomDeptEntityDo) Omit(cols ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleCustomDeptEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleCustomDeptEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleCustomDeptEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleCustomDeptEntityDo) Group(cols ...field.Expr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleCustomDeptEntityDo) Having(conds ...gen.Condition) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleCustomDeptEntityDo) Limit(limit int) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleCustomDeptEntityDo) Offset(offset int) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleCustomDeptEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleCustomDeptEntityDo) Unscoped() ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleCustomDeptEntityDo) Create(values ...*model.SysRoleCustomDeptEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleCustomDeptEntityDo) CreateInBatches(values []*model.SysRoleCustomDeptEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleCustomDeptEntityDo) Save(values ...*model.SysRoleCustomDeptEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleCustomDeptEntityDo) First() (*model.SysRoleCustomDeptEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleCustomDeptEntity), nil
	}
}

func (s sysRoleCustomDeptEntityDo) Take() (*model.SysRoleCustomDeptEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleCustomDeptEntity), nil
	}
}

func (s sysRoleCustomDeptEntityDo) Last() (*model.SysRoleCustomDeptEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleCustomDeptEntity), nil
	}
}

func (s sysRoleCustomDeptEntityDo) Find() ([]*model.SysRoleCustomDeptEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRoleCustomDeptEntity), err
}

func (s sysRoleCustomDeptEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleCustomDeptEntity, err error) {
	buf := make([]*model.SysRoleCustomDeptEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleCustomDeptEntityDo) FindInBatches(result *[]*model.SysRoleCustomDeptEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleCustomDeptEntityDo) Attrs(attrs ...field.AssignExpr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleCustomDeptEntityDo) Assign(attrs ...field.AssignExpr) ISysRoleCustomDeptEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleCustomDeptEntityDo) Joins(fields ...field.RelationField) ISysRoleCustomDeptEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleCustomDeptEntityDo) Preload(fields ...field.RelationField) ISysRoleCustomDeptEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleCustomDeptEntityDo) FirstOrInit() (*model.SysRoleCustomDeptEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleCustomDeptEntity), nil
	}
}

func (s sysRoleCustomDeptEntityDo) FirstOrCreate() (*model.SysRoleCustomDeptEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleCustomDeptEntity), nil
	}
}

func (s sysRoleCustomDeptEntityDo) FindByPage(offset int, limit int) (result []*model.SysRoleCustomDeptEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleCustomDeptEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleCustomDeptEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleCustomDeptEntityDo) Delete(models ...*model.SysRoleCustomDeptEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleCustomDeptEntityDo) withDO(do gen.Dao) *sysRoleCustomDeptEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
