// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysPostEntity(db *gorm.DB, opts ...gen.DOOption) sysPostEntity {
	_sysPostEntity := sysPostEntity{}

	_sysPostEntity.sysPostEntityDo.UseDB(db, opts...)
	_sysPostEntity.sysPostEntityDo.UseModel(&model.SysPostEntity{})

	tableName := _sysPostEntity.sysPostEntityDo.TableName()
	_sysPostEntity.ALL = field.NewAsterisk(tableName)
	_sysPostEntity.ID = field.NewInt64(tableName, "id")
	_sysPostEntity.Name = field.NewString(tableName, "name")
	_sysPostEntity.Code = field.NewString(tableName, "code")
	_sysPostEntity.Sort = field.NewInt64(tableName, "sort")
	_sysPostEntity.Status = field.NewInt64(tableName, "status")
	_sysPostEntity.Remark = field.NewString(tableName, "remark")
	_sysPostEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysPostEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysPostEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysPostEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysPostEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysPostEntity.fillFieldMap()

	return _sysPostEntity
}

// sysPostEntity 岗位表
type sysPostEntity struct {
	sysPostEntityDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键id
	Name      field.String // 岗位名称
	Code      field.String // 岗位编码
	Sort      field.Int64  // 排序
	Status    field.Int64  // 状态1正常 2禁用
	Remark    field.String // 备注
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 软删除时间
	CreatedBy field.Int64  // 创建人
	UpdatedBy field.Int64  // 更新人

	fieldMap map[string]field.Expr
}

func (s sysPostEntity) Table(newTableName string) *sysPostEntity {
	s.sysPostEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysPostEntity) As(alias string) *sysPostEntity {
	s.sysPostEntityDo.DO = *(s.sysPostEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysPostEntity) updateTableName(table string) *sysPostEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Name = field.NewString(table, "name")
	s.Code = field.NewString(table, "code")
	s.Sort = field.NewInt64(table, "sort")
	s.Status = field.NewInt64(table, "status")
	s.Remark = field.NewString(table, "remark")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysPostEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysPostEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["code"] = s.Code
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysPostEntity) clone(db *gorm.DB) sysPostEntity {
	s.sysPostEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysPostEntity) replaceDB(db *gorm.DB) sysPostEntity {
	s.sysPostEntityDo.ReplaceDB(db)
	return s
}

type sysPostEntityDo struct{ gen.DO }

type ISysPostEntityDo interface {
	gen.SubQuery
	Debug() ISysPostEntityDo
	WithContext(ctx context.Context) ISysPostEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysPostEntityDo
	WriteDB() ISysPostEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysPostEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysPostEntityDo
	Not(conds ...gen.Condition) ISysPostEntityDo
	Or(conds ...gen.Condition) ISysPostEntityDo
	Select(conds ...field.Expr) ISysPostEntityDo
	Where(conds ...gen.Condition) ISysPostEntityDo
	Order(conds ...field.Expr) ISysPostEntityDo
	Distinct(cols ...field.Expr) ISysPostEntityDo
	Omit(cols ...field.Expr) ISysPostEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysPostEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysPostEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysPostEntityDo
	Group(cols ...field.Expr) ISysPostEntityDo
	Having(conds ...gen.Condition) ISysPostEntityDo
	Limit(limit int) ISysPostEntityDo
	Offset(offset int) ISysPostEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysPostEntityDo
	Unscoped() ISysPostEntityDo
	Create(values ...*model.SysPostEntity) error
	CreateInBatches(values []*model.SysPostEntity, batchSize int) error
	Save(values ...*model.SysPostEntity) error
	First() (*model.SysPostEntity, error)
	Take() (*model.SysPostEntity, error)
	Last() (*model.SysPostEntity, error)
	Find() ([]*model.SysPostEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPostEntity, err error)
	FindInBatches(result *[]*model.SysPostEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysPostEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysPostEntityDo
	Assign(attrs ...field.AssignExpr) ISysPostEntityDo
	Joins(fields ...field.RelationField) ISysPostEntityDo
	Preload(fields ...field.RelationField) ISysPostEntityDo
	FirstOrInit() (*model.SysPostEntity, error)
	FirstOrCreate() (*model.SysPostEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysPostEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysPostEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysPostEntityDo) Debug() ISysPostEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysPostEntityDo) WithContext(ctx context.Context) ISysPostEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysPostEntityDo) ReadDB() ISysPostEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysPostEntityDo) WriteDB() ISysPostEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysPostEntityDo) Session(config *gorm.Session) ISysPostEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysPostEntityDo) Clauses(conds ...clause.Expression) ISysPostEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysPostEntityDo) Returning(value interface{}, columns ...string) ISysPostEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysPostEntityDo) Not(conds ...gen.Condition) ISysPostEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysPostEntityDo) Or(conds ...gen.Condition) ISysPostEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysPostEntityDo) Select(conds ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysPostEntityDo) Where(conds ...gen.Condition) ISysPostEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysPostEntityDo) Order(conds ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysPostEntityDo) Distinct(cols ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysPostEntityDo) Omit(cols ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysPostEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysPostEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysPostEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysPostEntityDo) Group(cols ...field.Expr) ISysPostEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysPostEntityDo) Having(conds ...gen.Condition) ISysPostEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysPostEntityDo) Limit(limit int) ISysPostEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysPostEntityDo) Offset(offset int) ISysPostEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysPostEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysPostEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysPostEntityDo) Unscoped() ISysPostEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysPostEntityDo) Create(values ...*model.SysPostEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysPostEntityDo) CreateInBatches(values []*model.SysPostEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysPostEntityDo) Save(values ...*model.SysPostEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysPostEntityDo) First() (*model.SysPostEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPostEntity), nil
	}
}

func (s sysPostEntityDo) Take() (*model.SysPostEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPostEntity), nil
	}
}

func (s sysPostEntityDo) Last() (*model.SysPostEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPostEntity), nil
	}
}

func (s sysPostEntityDo) Find() ([]*model.SysPostEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysPostEntity), err
}

func (s sysPostEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysPostEntity, err error) {
	buf := make([]*model.SysPostEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysPostEntityDo) FindInBatches(result *[]*model.SysPostEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysPostEntityDo) Attrs(attrs ...field.AssignExpr) ISysPostEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysPostEntityDo) Assign(attrs ...field.AssignExpr) ISysPostEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysPostEntityDo) Joins(fields ...field.RelationField) ISysPostEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysPostEntityDo) Preload(fields ...field.RelationField) ISysPostEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysPostEntityDo) FirstOrInit() (*model.SysPostEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPostEntity), nil
	}
}

func (s sysPostEntityDo) FirstOrCreate() (*model.SysPostEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysPostEntity), nil
	}
}

func (s sysPostEntityDo) FindByPage(offset int, limit int) (result []*model.SysPostEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysPostEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysPostEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysPostEntityDo) Delete(models ...*model.SysPostEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysPostEntityDo) withDO(do gen.Dao) *sysPostEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
