// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysAccountPostEntity(db *gorm.DB, opts ...gen.DOOption) sysAccountPostEntity {
	_sysAccountPostEntity := sysAccountPostEntity{}

	_sysAccountPostEntity.sysAccountPostEntityDo.UseDB(db, opts...)
	_sysAccountPostEntity.sysAccountPostEntityDo.UseModel(&model.SysAccountPostEntity{})

	tableName := _sysAccountPostEntity.sysAccountPostEntityDo.TableName()
	_sysAccountPostEntity.ALL = field.NewAsterisk(tableName)
	_sysAccountPostEntity.ID = field.NewInt64(tableName, "id")
	_sysAccountPostEntity.AccountID = field.NewInt64(tableName, "account_id")
	_sysAccountPostEntity.PostID = field.NewInt64(tableName, "post_id")
	_sysAccountPostEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysAccountPostEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysAccountPostEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysAccountPostEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysAccountPostEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysAccountPostEntity.fillFieldMap()

	return _sysAccountPostEntity
}

// sysAccountPostEntity 账号岗位关联表
type sysAccountPostEntity struct {
	sysAccountPostEntityDo

	ALL       field.Asterisk
	ID        field.Int64 // 主键id
	AccountID field.Int64 // 账号id
	PostID    field.Int64 // 岗位id
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Time  // 更新时间
	DeletedAt field.Field // 软删除时间
	CreatedBy field.Int64 // 创建人
	UpdatedBy field.Int64 // 更新人

	fieldMap map[string]field.Expr
}

func (s sysAccountPostEntity) Table(newTableName string) *sysAccountPostEntity {
	s.sysAccountPostEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAccountPostEntity) As(alias string) *sysAccountPostEntity {
	s.sysAccountPostEntityDo.DO = *(s.sysAccountPostEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAccountPostEntity) updateTableName(table string) *sysAccountPostEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.AccountID = field.NewInt64(table, "account_id")
	s.PostID = field.NewInt64(table, "post_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysAccountPostEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAccountPostEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["account_id"] = s.AccountID
	s.fieldMap["post_id"] = s.PostID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysAccountPostEntity) clone(db *gorm.DB) sysAccountPostEntity {
	s.sysAccountPostEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAccountPostEntity) replaceDB(db *gorm.DB) sysAccountPostEntity {
	s.sysAccountPostEntityDo.ReplaceDB(db)
	return s
}

type sysAccountPostEntityDo struct{ gen.DO }

type ISysAccountPostEntityDo interface {
	gen.SubQuery
	Debug() ISysAccountPostEntityDo
	WithContext(ctx context.Context) ISysAccountPostEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAccountPostEntityDo
	WriteDB() ISysAccountPostEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAccountPostEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAccountPostEntityDo
	Not(conds ...gen.Condition) ISysAccountPostEntityDo
	Or(conds ...gen.Condition) ISysAccountPostEntityDo
	Select(conds ...field.Expr) ISysAccountPostEntityDo
	Where(conds ...gen.Condition) ISysAccountPostEntityDo
	Order(conds ...field.Expr) ISysAccountPostEntityDo
	Distinct(cols ...field.Expr) ISysAccountPostEntityDo
	Omit(cols ...field.Expr) ISysAccountPostEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysAccountPostEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAccountPostEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAccountPostEntityDo
	Group(cols ...field.Expr) ISysAccountPostEntityDo
	Having(conds ...gen.Condition) ISysAccountPostEntityDo
	Limit(limit int) ISysAccountPostEntityDo
	Offset(offset int) ISysAccountPostEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAccountPostEntityDo
	Unscoped() ISysAccountPostEntityDo
	Create(values ...*model.SysAccountPostEntity) error
	CreateInBatches(values []*model.SysAccountPostEntity, batchSize int) error
	Save(values ...*model.SysAccountPostEntity) error
	First() (*model.SysAccountPostEntity, error)
	Take() (*model.SysAccountPostEntity, error)
	Last() (*model.SysAccountPostEntity, error)
	Find() ([]*model.SysAccountPostEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccountPostEntity, err error)
	FindInBatches(result *[]*model.SysAccountPostEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysAccountPostEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAccountPostEntityDo
	Assign(attrs ...field.AssignExpr) ISysAccountPostEntityDo
	Joins(fields ...field.RelationField) ISysAccountPostEntityDo
	Preload(fields ...field.RelationField) ISysAccountPostEntityDo
	FirstOrInit() (*model.SysAccountPostEntity, error)
	FirstOrCreate() (*model.SysAccountPostEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysAccountPostEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAccountPostEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAccountPostEntityDo) Debug() ISysAccountPostEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAccountPostEntityDo) WithContext(ctx context.Context) ISysAccountPostEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAccountPostEntityDo) ReadDB() ISysAccountPostEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAccountPostEntityDo) WriteDB() ISysAccountPostEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAccountPostEntityDo) Session(config *gorm.Session) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAccountPostEntityDo) Clauses(conds ...clause.Expression) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAccountPostEntityDo) Returning(value interface{}, columns ...string) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAccountPostEntityDo) Not(conds ...gen.Condition) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAccountPostEntityDo) Or(conds ...gen.Condition) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAccountPostEntityDo) Select(conds ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAccountPostEntityDo) Where(conds ...gen.Condition) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAccountPostEntityDo) Order(conds ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAccountPostEntityDo) Distinct(cols ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAccountPostEntityDo) Omit(cols ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAccountPostEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAccountPostEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAccountPostEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAccountPostEntityDo) Group(cols ...field.Expr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAccountPostEntityDo) Having(conds ...gen.Condition) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAccountPostEntityDo) Limit(limit int) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAccountPostEntityDo) Offset(offset int) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAccountPostEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAccountPostEntityDo) Unscoped() ISysAccountPostEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAccountPostEntityDo) Create(values ...*model.SysAccountPostEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAccountPostEntityDo) CreateInBatches(values []*model.SysAccountPostEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAccountPostEntityDo) Save(values ...*model.SysAccountPostEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAccountPostEntityDo) First() (*model.SysAccountPostEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountPostEntity), nil
	}
}

func (s sysAccountPostEntityDo) Take() (*model.SysAccountPostEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountPostEntity), nil
	}
}

func (s sysAccountPostEntityDo) Last() (*model.SysAccountPostEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountPostEntity), nil
	}
}

func (s sysAccountPostEntityDo) Find() ([]*model.SysAccountPostEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysAccountPostEntity), err
}

func (s sysAccountPostEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccountPostEntity, err error) {
	buf := make([]*model.SysAccountPostEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAccountPostEntityDo) FindInBatches(result *[]*model.SysAccountPostEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAccountPostEntityDo) Attrs(attrs ...field.AssignExpr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAccountPostEntityDo) Assign(attrs ...field.AssignExpr) ISysAccountPostEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAccountPostEntityDo) Joins(fields ...field.RelationField) ISysAccountPostEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAccountPostEntityDo) Preload(fields ...field.RelationField) ISysAccountPostEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAccountPostEntityDo) FirstOrInit() (*model.SysAccountPostEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountPostEntity), nil
	}
}

func (s sysAccountPostEntityDo) FirstOrCreate() (*model.SysAccountPostEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountPostEntity), nil
	}
}

func (s sysAccountPostEntityDo) FindByPage(offset int, limit int) (result []*model.SysAccountPostEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAccountPostEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAccountPostEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAccountPostEntityDo) Delete(models ...*model.SysAccountPostEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAccountPostEntityDo) withDO(do gen.Dao) *sysAccountPostEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
