// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysRoleResourcesEntity(db *gorm.DB, opts ...gen.DOOption) sysRoleResourcesEntity {
	_sysRoleResourcesEntity := sysRoleResourcesEntity{}

	_sysRoleResourcesEntity.sysRoleResourcesEntityDo.UseDB(db, opts...)
	_sysRoleResourcesEntity.sysRoleResourcesEntityDo.UseModel(&model.SysRoleResourcesEntity{})

	tableName := _sysRoleResourcesEntity.sysRoleResourcesEntityDo.TableName()
	_sysRoleResourcesEntity.ALL = field.NewAsterisk(tableName)
	_sysRoleResourcesEntity.ID = field.NewInt64(tableName, "id")
	_sysRoleResourcesEntity.ResourcesID = field.NewInt64(tableName, "resources_id")
	_sysRoleResourcesEntity.RoleID = field.NewInt64(tableName, "role_id")
	_sysRoleResourcesEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysRoleResourcesEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysRoleResourcesEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysRoleResourcesEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysRoleResourcesEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysRoleResourcesEntity.fillFieldMap()

	return _sysRoleResourcesEntity
}

// sysRoleResourcesEntity 角色和资源中间表
type sysRoleResourcesEntity struct {
	sysRoleResourcesEntityDo

	ALL         field.Asterisk
	ID          field.Int64 // 主键id
	ResourcesID field.Int64 // 关联到sys_resources表主键id
	RoleID      field.Int64 // 关联到sys_role表主键id
	CreatedAt   field.Time  // 创建时间
	UpdatedAt   field.Time  // 更新时间
	DeletedAt   field.Field // 软删除时间
	CreatedBy   field.Int64 // 创建人
	UpdatedBy   field.Int64 // 更新人

	fieldMap map[string]field.Expr
}

func (s sysRoleResourcesEntity) Table(newTableName string) *sysRoleResourcesEntity {
	s.sysRoleResourcesEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRoleResourcesEntity) As(alias string) *sysRoleResourcesEntity {
	s.sysRoleResourcesEntityDo.DO = *(s.sysRoleResourcesEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRoleResourcesEntity) updateTableName(table string) *sysRoleResourcesEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.ResourcesID = field.NewInt64(table, "resources_id")
	s.RoleID = field.NewInt64(table, "role_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysRoleResourcesEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRoleResourcesEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["resources_id"] = s.ResourcesID
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysRoleResourcesEntity) clone(db *gorm.DB) sysRoleResourcesEntity {
	s.sysRoleResourcesEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRoleResourcesEntity) replaceDB(db *gorm.DB) sysRoleResourcesEntity {
	s.sysRoleResourcesEntityDo.ReplaceDB(db)
	return s
}

type sysRoleResourcesEntityDo struct{ gen.DO }

type ISysRoleResourcesEntityDo interface {
	gen.SubQuery
	Debug() ISysRoleResourcesEntityDo
	WithContext(ctx context.Context) ISysRoleResourcesEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleResourcesEntityDo
	WriteDB() ISysRoleResourcesEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleResourcesEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleResourcesEntityDo
	Not(conds ...gen.Condition) ISysRoleResourcesEntityDo
	Or(conds ...gen.Condition) ISysRoleResourcesEntityDo
	Select(conds ...field.Expr) ISysRoleResourcesEntityDo
	Where(conds ...gen.Condition) ISysRoleResourcesEntityDo
	Order(conds ...field.Expr) ISysRoleResourcesEntityDo
	Distinct(cols ...field.Expr) ISysRoleResourcesEntityDo
	Omit(cols ...field.Expr) ISysRoleResourcesEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleResourcesEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleResourcesEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleResourcesEntityDo
	Group(cols ...field.Expr) ISysRoleResourcesEntityDo
	Having(conds ...gen.Condition) ISysRoleResourcesEntityDo
	Limit(limit int) ISysRoleResourcesEntityDo
	Offset(offset int) ISysRoleResourcesEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleResourcesEntityDo
	Unscoped() ISysRoleResourcesEntityDo
	Create(values ...*model.SysRoleResourcesEntity) error
	CreateInBatches(values []*model.SysRoleResourcesEntity, batchSize int) error
	Save(values ...*model.SysRoleResourcesEntity) error
	First() (*model.SysRoleResourcesEntity, error)
	Take() (*model.SysRoleResourcesEntity, error)
	Last() (*model.SysRoleResourcesEntity, error)
	Find() ([]*model.SysRoleResourcesEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleResourcesEntity, err error)
	FindInBatches(result *[]*model.SysRoleResourcesEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRoleResourcesEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleResourcesEntityDo
	Assign(attrs ...field.AssignExpr) ISysRoleResourcesEntityDo
	Joins(fields ...field.RelationField) ISysRoleResourcesEntityDo
	Preload(fields ...field.RelationField) ISysRoleResourcesEntityDo
	FirstOrInit() (*model.SysRoleResourcesEntity, error)
	FirstOrCreate() (*model.SysRoleResourcesEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysRoleResourcesEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleResourcesEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleResourcesEntityDo) Debug() ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleResourcesEntityDo) WithContext(ctx context.Context) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleResourcesEntityDo) ReadDB() ISysRoleResourcesEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleResourcesEntityDo) WriteDB() ISysRoleResourcesEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleResourcesEntityDo) Session(config *gorm.Session) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleResourcesEntityDo) Clauses(conds ...clause.Expression) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleResourcesEntityDo) Returning(value interface{}, columns ...string) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleResourcesEntityDo) Not(conds ...gen.Condition) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleResourcesEntityDo) Or(conds ...gen.Condition) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleResourcesEntityDo) Select(conds ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleResourcesEntityDo) Where(conds ...gen.Condition) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleResourcesEntityDo) Order(conds ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleResourcesEntityDo) Distinct(cols ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleResourcesEntityDo) Omit(cols ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleResourcesEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleResourcesEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleResourcesEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleResourcesEntityDo) Group(cols ...field.Expr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleResourcesEntityDo) Having(conds ...gen.Condition) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleResourcesEntityDo) Limit(limit int) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleResourcesEntityDo) Offset(offset int) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleResourcesEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleResourcesEntityDo) Unscoped() ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleResourcesEntityDo) Create(values ...*model.SysRoleResourcesEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleResourcesEntityDo) CreateInBatches(values []*model.SysRoleResourcesEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleResourcesEntityDo) Save(values ...*model.SysRoleResourcesEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleResourcesEntityDo) First() (*model.SysRoleResourcesEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleResourcesEntity), nil
	}
}

func (s sysRoleResourcesEntityDo) Take() (*model.SysRoleResourcesEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleResourcesEntity), nil
	}
}

func (s sysRoleResourcesEntityDo) Last() (*model.SysRoleResourcesEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleResourcesEntity), nil
	}
}

func (s sysRoleResourcesEntityDo) Find() ([]*model.SysRoleResourcesEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRoleResourcesEntity), err
}

func (s sysRoleResourcesEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleResourcesEntity, err error) {
	buf := make([]*model.SysRoleResourcesEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleResourcesEntityDo) FindInBatches(result *[]*model.SysRoleResourcesEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleResourcesEntityDo) Attrs(attrs ...field.AssignExpr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleResourcesEntityDo) Assign(attrs ...field.AssignExpr) ISysRoleResourcesEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleResourcesEntityDo) Joins(fields ...field.RelationField) ISysRoleResourcesEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleResourcesEntityDo) Preload(fields ...field.RelationField) ISysRoleResourcesEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleResourcesEntityDo) FirstOrInit() (*model.SysRoleResourcesEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleResourcesEntity), nil
	}
}

func (s sysRoleResourcesEntityDo) FirstOrCreate() (*model.SysRoleResourcesEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleResourcesEntity), nil
	}
}

func (s sysRoleResourcesEntityDo) FindByPage(offset int, limit int) (result []*model.SysRoleResourcesEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleResourcesEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleResourcesEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleResourcesEntityDo) Delete(models ...*model.SysRoleResourcesEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleResourcesEntityDo) withDO(do gen.Dao) *sysRoleResourcesEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
