// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gin-admin-api/internal/dal/model"
)

func newSysAccountRoleEntity(db *gorm.DB, opts ...gen.DOOption) sysAccountRoleEntity {
	_sysAccountRoleEntity := sysAccountRoleEntity{}

	_sysAccountRoleEntity.sysAccountRoleEntityDo.UseDB(db, opts...)
	_sysAccountRoleEntity.sysAccountRoleEntityDo.UseModel(&model.SysAccountRoleEntity{})

	tableName := _sysAccountRoleEntity.sysAccountRoleEntityDo.TableName()
	_sysAccountRoleEntity.ALL = field.NewAsterisk(tableName)
	_sysAccountRoleEntity.ID = field.NewInt64(tableName, "id")
	_sysAccountRoleEntity.AccountID = field.NewInt64(tableName, "account_id")
	_sysAccountRoleEntity.RoleID = field.NewInt64(tableName, "role_id")
	_sysAccountRoleEntity.CreatedAt = field.NewTime(tableName, "created_at")
	_sysAccountRoleEntity.UpdatedAt = field.NewTime(tableName, "updated_at")
	_sysAccountRoleEntity.DeletedAt = field.NewField(tableName, "deleted_at")
	_sysAccountRoleEntity.CreatedBy = field.NewInt64(tableName, "created_by")
	_sysAccountRoleEntity.UpdatedBy = field.NewInt64(tableName, "updated_by")

	_sysAccountRoleEntity.fillFieldMap()

	return _sysAccountRoleEntity
}

// sysAccountRoleEntity 账号和角色中间表
type sysAccountRoleEntity struct {
	sysAccountRoleEntityDo

	ALL       field.Asterisk
	ID        field.Int64 // 主键id
	AccountID field.Int64 // 关联到sys_account表主键id
	RoleID    field.Int64 // 关联到sys_role表主键id
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Time  // 更新时间
	DeletedAt field.Field // 软删除时间
	CreatedBy field.Int64 // 创建人
	UpdatedBy field.Int64 // 更新人

	fieldMap map[string]field.Expr
}

func (s sysAccountRoleEntity) Table(newTableName string) *sysAccountRoleEntity {
	s.sysAccountRoleEntityDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAccountRoleEntity) As(alias string) *sysAccountRoleEntity {
	s.sysAccountRoleEntityDo.DO = *(s.sysAccountRoleEntityDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAccountRoleEntity) updateTableName(table string) *sysAccountRoleEntity {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.AccountID = field.NewInt64(table, "account_id")
	s.RoleID = field.NewInt64(table, "role_id")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedBy = field.NewInt64(table, "created_by")
	s.UpdatedBy = field.NewInt64(table, "updated_by")

	s.fillFieldMap()

	return s
}

func (s *sysAccountRoleEntity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAccountRoleEntity) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["account_id"] = s.AccountID
	s.fieldMap["role_id"] = s.RoleID
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_by"] = s.CreatedBy
	s.fieldMap["updated_by"] = s.UpdatedBy
}

func (s sysAccountRoleEntity) clone(db *gorm.DB) sysAccountRoleEntity {
	s.sysAccountRoleEntityDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAccountRoleEntity) replaceDB(db *gorm.DB) sysAccountRoleEntity {
	s.sysAccountRoleEntityDo.ReplaceDB(db)
	return s
}

type sysAccountRoleEntityDo struct{ gen.DO }

type ISysAccountRoleEntityDo interface {
	gen.SubQuery
	Debug() ISysAccountRoleEntityDo
	WithContext(ctx context.Context) ISysAccountRoleEntityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAccountRoleEntityDo
	WriteDB() ISysAccountRoleEntityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAccountRoleEntityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAccountRoleEntityDo
	Not(conds ...gen.Condition) ISysAccountRoleEntityDo
	Or(conds ...gen.Condition) ISysAccountRoleEntityDo
	Select(conds ...field.Expr) ISysAccountRoleEntityDo
	Where(conds ...gen.Condition) ISysAccountRoleEntityDo
	Order(conds ...field.Expr) ISysAccountRoleEntityDo
	Distinct(cols ...field.Expr) ISysAccountRoleEntityDo
	Omit(cols ...field.Expr) ISysAccountRoleEntityDo
	Join(table schema.Tabler, on ...field.Expr) ISysAccountRoleEntityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAccountRoleEntityDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAccountRoleEntityDo
	Group(cols ...field.Expr) ISysAccountRoleEntityDo
	Having(conds ...gen.Condition) ISysAccountRoleEntityDo
	Limit(limit int) ISysAccountRoleEntityDo
	Offset(offset int) ISysAccountRoleEntityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAccountRoleEntityDo
	Unscoped() ISysAccountRoleEntityDo
	Create(values ...*model.SysAccountRoleEntity) error
	CreateInBatches(values []*model.SysAccountRoleEntity, batchSize int) error
	Save(values ...*model.SysAccountRoleEntity) error
	First() (*model.SysAccountRoleEntity, error)
	Take() (*model.SysAccountRoleEntity, error)
	Last() (*model.SysAccountRoleEntity, error)
	Find() ([]*model.SysAccountRoleEntity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccountRoleEntity, err error)
	FindInBatches(result *[]*model.SysAccountRoleEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysAccountRoleEntity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAccountRoleEntityDo
	Assign(attrs ...field.AssignExpr) ISysAccountRoleEntityDo
	Joins(fields ...field.RelationField) ISysAccountRoleEntityDo
	Preload(fields ...field.RelationField) ISysAccountRoleEntityDo
	FirstOrInit() (*model.SysAccountRoleEntity, error)
	FirstOrCreate() (*model.SysAccountRoleEntity, error)
	FindByPage(offset int, limit int) (result []*model.SysAccountRoleEntity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAccountRoleEntityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAccountRoleEntityDo) Debug() ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAccountRoleEntityDo) WithContext(ctx context.Context) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAccountRoleEntityDo) ReadDB() ISysAccountRoleEntityDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAccountRoleEntityDo) WriteDB() ISysAccountRoleEntityDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAccountRoleEntityDo) Session(config *gorm.Session) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAccountRoleEntityDo) Clauses(conds ...clause.Expression) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAccountRoleEntityDo) Returning(value interface{}, columns ...string) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAccountRoleEntityDo) Not(conds ...gen.Condition) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAccountRoleEntityDo) Or(conds ...gen.Condition) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAccountRoleEntityDo) Select(conds ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAccountRoleEntityDo) Where(conds ...gen.Condition) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAccountRoleEntityDo) Order(conds ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAccountRoleEntityDo) Distinct(cols ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAccountRoleEntityDo) Omit(cols ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAccountRoleEntityDo) Join(table schema.Tabler, on ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAccountRoleEntityDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAccountRoleEntityDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAccountRoleEntityDo) Group(cols ...field.Expr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAccountRoleEntityDo) Having(conds ...gen.Condition) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAccountRoleEntityDo) Limit(limit int) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAccountRoleEntityDo) Offset(offset int) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAccountRoleEntityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAccountRoleEntityDo) Unscoped() ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAccountRoleEntityDo) Create(values ...*model.SysAccountRoleEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAccountRoleEntityDo) CreateInBatches(values []*model.SysAccountRoleEntity, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAccountRoleEntityDo) Save(values ...*model.SysAccountRoleEntity) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAccountRoleEntityDo) First() (*model.SysAccountRoleEntity, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountRoleEntity), nil
	}
}

func (s sysAccountRoleEntityDo) Take() (*model.SysAccountRoleEntity, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountRoleEntity), nil
	}
}

func (s sysAccountRoleEntityDo) Last() (*model.SysAccountRoleEntity, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountRoleEntity), nil
	}
}

func (s sysAccountRoleEntityDo) Find() ([]*model.SysAccountRoleEntity, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysAccountRoleEntity), err
}

func (s sysAccountRoleEntityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAccountRoleEntity, err error) {
	buf := make([]*model.SysAccountRoleEntity, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAccountRoleEntityDo) FindInBatches(result *[]*model.SysAccountRoleEntity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAccountRoleEntityDo) Attrs(attrs ...field.AssignExpr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAccountRoleEntityDo) Assign(attrs ...field.AssignExpr) ISysAccountRoleEntityDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAccountRoleEntityDo) Joins(fields ...field.RelationField) ISysAccountRoleEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAccountRoleEntityDo) Preload(fields ...field.RelationField) ISysAccountRoleEntityDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAccountRoleEntityDo) FirstOrInit() (*model.SysAccountRoleEntity, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountRoleEntity), nil
	}
}

func (s sysAccountRoleEntityDo) FirstOrCreate() (*model.SysAccountRoleEntity, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAccountRoleEntity), nil
	}
}

func (s sysAccountRoleEntityDo) FindByPage(offset int, limit int) (result []*model.SysAccountRoleEntity, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAccountRoleEntityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAccountRoleEntityDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAccountRoleEntityDo) Delete(models ...*model.SysAccountRoleEntity) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAccountRoleEntityDo) withDO(do gen.Dao) *sysAccountRoleEntityDo {
	s.DO = *do.(*gen.DO)
	return s
}
