// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCasbinRuleEntity = "casbin_rule"

// CasbinRuleEntity mapped from table <casbin_rule>
type CasbinRuleEntity struct {
	ID    int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Ptype string `gorm:"column:ptype;type:varchar(100)" json:"ptype"`
	V0    string `gorm:"column:v0;type:varchar(100)" json:"v0"`
	V1    string `gorm:"column:v1;type:varchar(100)" json:"v1"`
	V2    string `gorm:"column:v2;type:varchar(100)" json:"v2"`
	V3    string `gorm:"column:v3;type:varchar(100)" json:"v3"`
	V4    string `gorm:"column:v4;type:varchar(100)" json:"v4"`
	V5    string `gorm:"column:v5;type:varchar(100)" json:"v5"`
}

// TableName CasbinRuleEntity's table name
func (*CasbinRuleEntity) TableName() string {
	return TableNameCasbinRuleEntity
}
