// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysResourcesEntity = "sys_resources"

// SysResourcesEntity 资源表
type SysResourcesEntity struct {
	ID            int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                        // 主键id
	Title         string         `gorm:"column:title;type:varchar(50);not null;comment:名称:按钮标题,或菜单标题" json:"title"`                      // 名称:按钮标题,或菜单标题
	URL           string         `gorm:"column:url;type:varchar(100);not null;comment:按钮请求url,或菜单路由" json:"url"`                         // 按钮请求url,或菜单路由
	Method        string         `gorm:"column:method;type:varchar(50);comment:接口的请求方式" json:"method"`                                   // 接口的请求方式
	Icon          string         `gorm:"column:icon;type:varchar(100);comment:菜单小图标" json:"icon"`                                        // 菜单小图标
	ResourcesType int64          `gorm:"column:resources_type;type:tinyint;default:1;comment:类型:1表示目录,2表示菜单,3表示接口" json:"resourcesType"` // 类型:1表示目录,2表示菜单,3表示接口
	IsCache       int64          `gorm:"column:is_cache;type:tinyint;default:1;comment:是否缓存:1表示缓存:2不缓存" json:"isCache"`                  // 是否缓存:1表示缓存:2不缓存
	IsHidden      int64          `gorm:"column:is_hidden;type:tinyint;default:1;comment:是否隐藏:1表示不隐藏,2表示隐藏" json:"isHidden"`              // 是否隐藏:1表示不隐藏,2表示隐藏
	IsLink        int64          `gorm:"column:is_link;type:tinyint;default:1;comment:是否为外部链接:1表示不是,2表示是" json:"isLink"`                 // 是否为外部链接:1表示不是,2表示是
	ParentID      int64          `gorm:"column:parent_id;type:int;not null;comment:上一级id，0=顶级" json:"parentId"`                          // 上一级id，0=顶级
	Sort          int64          `gorm:"column:sort;type:int;default:1;comment:菜单,或按钮排序" json:"sort"`                                    // 菜单,或按钮排序
	Status        int64          `gorm:"column:status;type:tinyint;default:1;comment:状态1是正常,2是禁用" json:"status"`                         // 状态1是正常,2是禁用
	Description   string         `gorm:"column:description;type:varchar(200);comment:描述" json:"description"`                             // 描述
	IsAdminHave   int64          `gorm:"column:is_admin_have;type:tinyint;comment:是否超管独有,1表示是,0表示不是" json:"isAdminHave"`                 // 是否超管独有,1表示是,0表示不是
	CreatedAt     time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                                // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                                // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                                         // 软删除时间
	CreatedBy     int64          `gorm:"column:created_by;type:int;comment:创建人" json:"createdBy"`                                        // 创建人
	UpdatedBy     int64          `gorm:"column:updated_by;type:int;comment:更新人" json:"updatedBy"`                                        // 更新人
}

// TableName SysResourcesEntity's table name
func (*SysResourcesEntity) TableName() string {
	return TableNameSysResourcesEntity
}
