// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysPostEntity = "sys_post"

// SysPostEntity 岗位表
type SysPostEntity struct {
	ID        int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Name      string         `gorm:"column:name;type:varchar(50);not null;comment:岗位名称" json:"name"`          // 岗位名称
	Code      string         `gorm:"column:code;type:varchar(60);not null;comment:岗位编码" json:"code"`          // 岗位编码
	Sort      int64          `gorm:"column:sort;type:int;default:1;comment:排序" json:"sort"`                   // 排序
	Status    int64          `gorm:"column:status;type:tinyint;default:1;comment:状态1正常 2禁用" json:"status"`    // 状态1正常 2禁用
	Remark    string         `gorm:"column:remark;type:varchar(255);comment:备注" json:"remark"`                // 备注
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                         // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                         // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                  // 软删除时间
	CreatedBy int64          `gorm:"column:created_by;type:int;comment:创建人" json:"createdBy"`                 // 创建人
	UpdatedBy int64          `gorm:"column:updated_by;type:int;comment:更新人" json:"updatedBy"`                 // 更新人
}

// TableName SysPostEntity's table name
func (*SysPostEntity) TableName() string {
	return TableNameSysPostEntity
}
