// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysAccountRoleEntity = "sys_account_role"

// SysAccountRoleEntity 账号和角色中间表
type SysAccountRoleEntity struct {
	ID        int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"`          // 主键id
	AccountID int64          `gorm:"column:account_id;type:int;not null;comment:关联到sys_account表主键id" json:"accountId"` // 关联到sys_account表主键id
	RoleID    int64          `gorm:"column:role_id;type:int;not null;comment:关联到sys_role表主键id" json:"roleId"`          // 关联到sys_role表主键id
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                  // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                  // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                           // 软删除时间
	CreatedBy int64          `gorm:"column:created_by;type:int;comment:创建人" json:"createdBy"`                          // 创建人
	UpdatedBy int64          `gorm:"column:updated_by;type:int;comment:更新人" json:"updatedBy"`                          // 更新人
}

// TableName SysAccountRoleEntity's table name
func (*SysAccountRoleEntity) TableName() string {
	return TableNameSysAccountRoleEntity
}
