// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysDeptEntity = "sys_dept"

// SysDeptEntity 部门表
type SysDeptEntity struct {
	ID        int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"`        // 主键id
	Name      string         `gorm:"column:name;type:varchar(50);not null;comment:部门名称" json:"name"`                 // 部门名称
	ParentID  int64          `gorm:"column:parent_id;type:int;not null;comment:上级部门id" json:"parentId"`              // 上级部门id
	FullID    string         `gorm:"column:full_id;type:varchar(255);not null;comment:全层级ID，例：1,5,12" json:"fullId"` // 全层级ID，例：1,5,12
	FullName  string         `gorm:"column:full_name;type:varchar(255);not null;comment:全层级名称" json:"fullName"`      // 全层级名称
	Sort      int64          `gorm:"column:sort;type:int;default:1;comment:排序" json:"sort"`                          // 排序
	Status    int64          `gorm:"column:status;type:tinyint;default:1;comment:状态1正常 2禁用" json:"status"`           // 状态1正常 2禁用
	LeaderID  int64          `gorm:"column:leader_id;type:int;comment:负责人账号id，关联sys_account.id" json:"leaderId"`     // 负责人账号id，关联sys_account.id
	Phone     string         `gorm:"column:phone;type:varchar(20);comment:联系电话" json:"phone"`                        // 联系电话
	Email     string         `gorm:"column:email;type:varchar(60);comment:邮箱" json:"email"`                          // 邮箱
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                         // 软删除时间
	CreatedBy int64          `gorm:"column:created_by;type:int;comment:创建人" json:"createdBy"`                        // 创建人
	UpdatedBy int64          `gorm:"column:updated_by;type:int;comment:更新人" json:"updatedBy"`                        // 更新人
}

// TableName SysDeptEntity's table name
func (*SysDeptEntity) TableName() string {
	return TableNameSysDeptEntity
}
