// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRoleEntity = "sys_role"

// SysRoleEntity 角色表
type SysRoleEntity struct {
	ID          int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Name        string         `gorm:"column:name;type:varchar(50);not null;comment:角色名称" json:"name"`          // 角色名称
	Description string         `gorm:"column:description;type:varchar(255);comment:描述" json:"description"`      // 描述
	Status      int64          `gorm:"column:status;type:tinyint;default:1;comment:状态1是正常,2是禁用" json:"status"`  // 状态1是正常,2是禁用
	Sort        int64          `gorm:"column:sort;type:int;default:1;comment:排序" json:"sort"`                   // 排序
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                         // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                         // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                  // 软删除时间
	CreatedBy   int64          `gorm:"column:created_by;type:int;comment:创建人" json:"createdBy"`                 // 创建人
	UpdatedBy   int64          `gorm:"column:updated_by;type:int;comment:更新人" json:"updatedBy"`                 // 更新人
}

// TableName SysRoleEntity's table name
func (*SysRoleEntity) TableName() string {
	return TableNameSysRoleEntity
}
