// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRoleCustomDeptEntity = "sys_role_custom_dept"

// SysRoleCustomDeptEntity 角色自定义数据权限部门表
type SysRoleCustomDeptEntity struct {
	ID        int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	RoleID    int64          `gorm:"column:role_id;type:int;not null;comment:角色id" json:"roleId"`             // 角色id
	DeptID    int64          `gorm:"column:dept_id;type:int;not null;comment:可查看部门id" json:"deptId"`          // 可查看部门id
	CreatedAt time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                         // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                         // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                  // 软删除时间
}

// TableName SysRoleCustomDeptEntity's table name
func (*SysRoleCustomDeptEntity) TableName() string {
	return TableNameSysRoleCustomDeptEntity
}
