// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRoleResourcesEntity = "sys_role_resources"

// SysRoleResourcesEntity 角色和资源中间表
type SysRoleResourcesEntity struct {
	ID          int64          `gorm:"column:id;type:int;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                // 主键id
	ResourcesID int64          `gorm:"column:resources_id;type:int;not null;comment:关联到sys_resources表主键id" json:"resourcesId"` // 关联到sys_resources表主键id
	RoleID      int64          `gorm:"column:role_id;type:int;not null;comment:关联到sys_role表主键id" json:"roleId"`                // 关联到sys_role表主键id
	CreatedAt   time.Time      `gorm:"column:created_at;comment:创建时间" json:"createdAt"`                                        // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;comment:更新时间" json:"updatedAt"`                                        // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:软删除时间" json:"-"`                                 // 软删除时间
	CreatedBy   int64          `gorm:"column:created_by;type:int;comment:创建人" json:"createdBy"`                                // 创建人
	UpdatedBy   int64          `gorm:"column:updated_by;type:int;comment:更新人" json:"updatedBy"`                                // 更新人
}

// TableName SysRoleResourcesEntity's table name
func (*SysRoleResourcesEntity) TableName() string {
	return TableNameSysRoleResourcesEntity
}
