// Code generated by gorm-plus generator. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"github.com/kuangshp/gorm-plus"
	"gorm.io/gen"
	"gin-admin-api/internal/dal/dao"
	"gin-admin-api/internal/dal/model"
)

type defaultCasbinRuleRepository struct {
}

type iDefaultCasbinRuleRepository interface {
	// Create 创建记录（自动失效 FindList / FindPage / Count / Exists 前缀缓存）
	Create(ctx context.Context, m *model.CasbinRuleEntity, opts ...gormplus.CreateOption) error
	CreateTx(ctx context.Context, tx *dao.Query, m *model.CasbinRuleEntity, opts ...gormplus.CreateOption) error
	// CreateBatch 批量创建（自动失效 FindList / FindPage / Count / Exists 前缀缓存）
	CreateBatch(ctx context.Context, m []*model.CasbinRuleEntity, opts ...gormplus.CreateOption) error
	CreateBatchTx(ctx context.Context, tx *dao.Query, m []*model.CasbinRuleEntity, opts ...gormplus.CreateOption) error
	// DeleteById 根据ID删除（默认软删除；传 gormplus.Delete().WithPhysicalDelete().Build() 时物理删除。自动失效该 ID 的 FindById，以及 FindList/FindPage/Count/Exists 前缀缓存）
	DeleteById(ctx context.Context, casbinRuleId int64, opts ...gormplus.DeleteOption) error
	DeleteByIdTx(ctx context.Context, tx *dao.Query, casbinRuleId int64, opts ...gormplus.DeleteOption) error
	// DeleteByIdList 根据ID列表批量删除（自动失效每个 ID 的 FindById，以及 FindList/FindPage/Count/Exists 前缀缓存）
	DeleteByIdList(ctx context.Context, casbinRuleIds []int64, opts ...gormplus.DeleteOption) error
	DeleteByIdListTx(ctx context.Context, tx *dao.Query, casbinRuleIds []int64, opts ...gormplus.DeleteOption) error
	// DeleteByCondition 根据原生条件删除（默认软删除；传 gormplus.Delete().WithPhysicalDelete().Build() 时物理删除。自动按表名前缀失效全部缓存，因无法预知影响的 ID）
	DeleteByCondition(ctx context.Context, cond ...gen.Condition) error
	DeleteByConditionTx(ctx context.Context, tx *dao.Query, cond ...gen.Condition) error
	// DeleteByWrapper 根据wrapper条件删除（默认软删除；传 gormplus.Delete().WithPhysicalDelete().Build() 时物理删除。自动按表名前缀失效全部缓存，因无法预知影响的 ID）
	DeleteByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.DeleteOption) error
	DeleteByWrapperTx(ctx context.Context, tx *dao.Query, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.DeleteOption) error
	// UpdateById 根据ID更新指定字段（自动失效该 ID 的 FindById，以及 FindList/FindPage 前缀缓存）
	UpdateById(ctx context.Context, casbinRuleId int64, opts ...gormplus.UpdateOption) error
	UpdateByIdTx(ctx context.Context, tx *dao.Query, casbinRuleId int64, opts ...gormplus.UpdateOption) error
	// UpdateMapById 根据ID更新Map数据（自动失效该 ID 的 FindById，以及 FindList/FindPage 前缀缓存）
	UpdateMapById(ctx context.Context, casbinRuleId int64, data map[string]any) error
	UpdateMapByIdTx(ctx context.Context, tx *dao.Query, casbinRuleId int64, data map[string]any) error
	// UpdateByWrapper 根据wrapper条件更新（自动按表名前缀失效全部缓存，因无法预知影响的 ID）
	UpdateByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.UpdateOption) error
	UpdateByWrapperTx(ctx context.Context, tx *dao.Query, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.UpdateOption) error
	// FindList 根据原生条件获取列表
	FindList(ctx context.Context, query ...gormplus.QueryOption) ([]*model.CasbinRuleEntity, error)
	// FindListByWrapper 根据wrapper条件获取列表
	FindListByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) ([]*model.CasbinRuleEntity, error)
	// FindPage 根据原生条件分页查询
	FindPage(ctx context.Context, pageNumber int64, pageSize int64, query ...gormplus.QueryOption) (list []*model.CasbinRuleEntity, total int64, err error)
	// FindPageByWrapper 根据wrapper条件分页查询
	FindPageByWrapper(ctx context.Context, pageNumber int64, pageSize int64, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (list []*model.CasbinRuleEntity, total int64, err error)
	// FindById 根据ID获取详情（支持 query.WithCache / query.WithSingleFlight）
	FindById(ctx context.Context, casbinRuleId int64, query ...gormplus.QueryOption) (*model.CasbinRuleEntity, error)
	// FindByIdList 根据ID列表获取（支持 query.WithCache / query.WithSingleFlight）
	FindByIdList(ctx context.Context, casbinRuleIds []int64, query ...gormplus.QueryOption) ([]*model.CasbinRuleEntity, error)
	// FindOne 根据原生条件获取单条
	FindOne(ctx context.Context, query ...gormplus.QueryOption) (*model.CasbinRuleEntity, error)
	// FindOneWrapper 根据wrapper条件获取单条
	FindOneWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (*model.CasbinRuleEntity, error)
	// Exists 根据原生条件判断是否存在（支持 query.WithCache / query.WithSingleFlight）
	Exists(ctx context.Context, query ...gormplus.QueryOption) (bool, error)
	// ExistsByWrapper 根据wrapper条件判断是否存在（支持 query.WithCache / query.WithSingleFlight）
	ExistsByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (bool, error)
	// Count 根据原生条件统计数量（支持 query.WithCache / query.WithSingleFlight）
	Count(ctx context.Context, query ...gormplus.QueryOption) (int64, error)
	// CountByWrapper 根据wrapper条件统计数量（支持 query.WithCache / query.WithSingleFlight）
	CountByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (int64, error)
}

// ==================== 缓存失效辅助方法 ====================
//
// 缓存策略总览（统一以 "casbin_rule.方法名" 为 fnName）：
//
//	写操作              失效范围
//	──────────         ─────────────────────────────────────────────────────────
//	Create / Update     invalidateWriteCaches：清 List/Page/Count/Exists 全部前缀
//	  / Delete (by id)  + 单条 FindById（精确）
//	条件 Update/Delete  invalidateAllTableCaches：整张表（按表名前缀失效）
//
// 设计说明：
//   - 三类写操作的 List/Aggregate 失效范围相同，合并成一个函数，避免 Redis 多次 SCAN
//   - 用 SFInvalidatePrefixes 批量接口：Redis 场景下从 11 次 SCAN 降为 1 次 pipeline
//   - 关于 Update 清 Count/Exists：软删除场景（deleted_at 字段更新）走的就是 Update，
//     若不清 Count/Exists 会导致"删了但 Count 还是旧值"，所以宁可保守失效

// invalidateWriteCaches 失效所有受写操作影响的缓存（List / Page / Count / Exists + 衍生方法）。
// 用于 Create / Update / Delete 三类已知 ID 的写操作。
func (r *defaultCasbinRuleRepository) invalidateWriteCaches() {
	gormplus.SFInvalidatePrefixes([]string{
		"casbin_rule.FindList",
		"casbin_rule.FindListByWrapper",
		"casbin_rule.FindPage",
		"casbin_rule.FindPageByWrapper",
		"casbin_rule.FindByIdList",
		"casbin_rule.FindOne",
		"casbin_rule.FindOneWrapper",
		"casbin_rule.Count",
		"casbin_rule.CountByWrapper",
		"casbin_rule.Exists",
		"casbin_rule.ExistsByWrapper",
	})
}

// invalidateAllTableCaches 失效整张表所有缓存（用于条件 Update / Delete，无法预知影响的 ID）。
// 包括 FindById 在内的所有方法都会被清掉。
func (r *defaultCasbinRuleRepository) invalidateAllTableCaches() {
	gormplus.SFInvalidatePrefix("casbin_rule.")
}

// ==================== 公共构建方法 ====================

func (r *defaultCasbinRuleRepository) buildTx(ctx context.Context, query []gormplus.QueryOption) dao.ICasbinRuleEntityDo {
	if len(query) == 0 {
		return dao.CasbinRuleEntity.WithContext(ctx).Order(dao.CasbinRuleEntity.ID.Desc())
	}
	q := gormplus.MergeQueryOptions(query...)
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if q.Unscoped {
		tx = tx.Unscoped()
	}
	if len(q.Clauses) > 0 {
		tx = tx.Clauses(q.Clauses...)
	}
	if len(q.Cond) > 0 {
		tx = tx.Where(q.Cond...)
	}
	if len(q.Select) > 0 {
		tx = tx.Select(q.Select...)
	}
	if len(q.OmitFields) > 0 {
		tx = tx.Omit(q.OmitFields...)
	}
	if len(q.Order) > 0 {
		tx = tx.Order(q.Order...)
	} else {
		tx = tx.Order(dao.CasbinRuleEntity.ID.Desc())
	}
	if q.Limit != nil {
		tx = tx.Limit(*q.Limit)
	}
	return tx
}

func (r *defaultCasbinRuleRepository) buildWrapperTx(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query []gormplus.QueryOption) dao.ICasbinRuleEntityDo {
	q := gormplus.MergeQueryOptions(query...)
	baseTx := dao.CasbinRuleEntity.WithContext(ctx)
	if q.Unscoped {
		baseTx = baseTx.Unscoped()
	}
	if len(q.Clauses) > 0 {
		baseTx = baseTx.Clauses(q.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if q.Unscoped {
		tx.WithDeleted()
	}

    if fn != nil {
        fn(tx)
    }
    entityDo := tx.Apply()
    if len(query) > 0 {
        if len(q.Cond) > 0 {
            entityDo = entityDo.Where(q.Cond...)
        }
        if len(q.Select) > 0 {
            entityDo = entityDo.Select(q.Select...)
        }
        if len(q.OmitFields) > 0 {
            entityDo = entityDo.Omit(q.OmitFields...)
        }
        if len(q.Order) > 0 {
            entityDo = entityDo.Order(q.Order...)
        } else {
            entityDo = entityDo.Order(dao.CasbinRuleEntity.ID.Desc())
        }
        if q.Limit != nil {
            entityDo = entityDo.Limit(*q.Limit)
        }
    }
	return entityDo
}

// ==================== 实现 ====================

func (r *defaultCasbinRuleRepository) Create(ctx context.Context, m *model.CasbinRuleEntity, opts ...gormplus.CreateOption) error {
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.Create(m)
	if err == nil {
		// 新增：列表/分页 + 数量/存在性缓存全部失效
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) CreateTx(ctx context.Context, daoTx *dao.Query, m *model.CasbinRuleEntity, opts ...gormplus.CreateOption) error {
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.Create(m)
	if err == nil {
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) CreateBatch(ctx context.Context, m []*model.CasbinRuleEntity, opts ...gormplus.CreateOption) error {
	if len(m) == 0 {
		return nil
	}
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.CreateInBatches(m, len(m))
	if err == nil {
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) CreateBatchTx(ctx context.Context, daoTx *dao.Query, m []*model.CasbinRuleEntity, opts ...gormplus.CreateOption) error {
	if len(m) == 0 {
		return nil
	}
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.CreateInBatches(m, len(m))
	if err == nil {
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteById(ctx context.Context, casbinRuleId int64, opts ...gormplus.DeleteOption) error {
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
	).Delete()
	if err == nil {
		// 删除：单条精确失效 + 列表/分页前缀失效 + 数量/存在性前缀失效
		gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", casbinRuleId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteByIdTx(ctx context.Context, daoTx *dao.Query, casbinRuleId int64, opts ...gormplus.DeleteOption) error {
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
	).Delete()
	if err == nil {
		gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", casbinRuleId))
		r.invalidateWriteCaches()
	}
	return err
}
func (r *defaultCasbinRuleRepository) DeleteByIdList(ctx context.Context, casbinRuleIds []int64, opts ...gormplus.DeleteOption) error {
	if len(casbinRuleIds) == 0 {
		return nil
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(dao.CasbinRuleEntity.ID.In(casbinRuleIds...)).Delete()
	if err == nil {
		for _, id := range casbinRuleIds {
			gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", id))
		}
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteByIdListTx(ctx context.Context, daoTx *dao.Query, casbinRuleIds []int64, opts ...gormplus.DeleteOption) error {
	if len(casbinRuleIds) == 0 {
		return nil
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(dao.CasbinRuleEntity.ID.In(casbinRuleIds...)).Delete()
	if err == nil {
		for _, id := range casbinRuleIds {
			gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", id))
		}
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteByCondition(ctx context.Context, cond ...gen.Condition) error {
	cond, deleteOpts := gormplus.SplitDeleteConditions(cond)
	if len(cond) == 0 {
		return errors.New("删除条件不能为空")
	}
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(cond...).Delete()
	if err == nil {
		// 条件删除无法预知影响哪些 ID，全表缓存清掉最安全
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteByConditionTx(ctx context.Context, daoTx *dao.Query, cond ...gen.Condition) error {
	cond, deleteOpts := gormplus.SplitDeleteConditions(cond)
	if len(cond) == 0 {
		return errors.New("删除条件不能为空")
	}
	tx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(cond...).Delete()
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.DeleteOption) error {
	if fn == nil {
		return errors.New("删除条件不能为空")
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	baseTx := dao.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		baseTx = baseTx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(deleteOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if deleteOpts.Physical {
		tx.WithDeleted()
	}
	fn(tx)
	_, err := tx.Apply().Delete()
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) DeleteByWrapperTx(ctx context.Context, daoTx *dao.Query, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.DeleteOption) error {
	if fn == nil {
		return errors.New("删除条件不能为空")
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	baseTx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if deleteOpts.Physical {
		baseTx = baseTx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(deleteOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if deleteOpts.Physical {
		tx.WithDeleted()
	}
	fn(tx)
	_, err := tx.Apply().Delete()
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) UpdateById(ctx context.Context, casbinRuleId int64, opts ...gormplus.UpdateOption) error {
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	tx := dao.CasbinRuleEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		tx = tx.Clauses(updateOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
	).UpdateSimple(updateOpts.Columns...)
	if err == nil {
		// 修改：单条精确失效 + 列表/分页前缀失效（数量/存在性一般不受影响）
		gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", casbinRuleId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) UpdateByIdTx(ctx context.Context, daoTx *dao.Query, casbinRuleId int64, opts ...gormplus.UpdateOption) error {
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	tx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		tx = tx.Clauses(updateOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
	).UpdateSimple(updateOpts.Columns...)
	if err == nil {
		gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", casbinRuleId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) UpdateMapById(ctx context.Context, casbinRuleId int64, data map[string]any) error {
	if len(data) == 0 {
		return nil
	}
	_, err := dao.CasbinRuleEntity.WithContext(ctx).
		Where(
			dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
		).
		Updates(data)
	if err == nil {
		gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", casbinRuleId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) UpdateMapByIdTx(ctx context.Context, daoTx *dao.Query, casbinRuleId int64, data map[string]any) error {
	if len(data) == 0 {
		return nil
	}
	_, err := daoTx.CasbinRuleEntity.WithContext(ctx).
		Where(
			dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
		).
		Updates(data)
	if err == nil {
		gormplus.SFInvalidate("casbin_rule.FindById", gormplus.BuildArgs("id", casbinRuleId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) UpdateByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.UpdateOption) error {
	if fn == nil {
		return errors.New("更新条件不能为空")
	}
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	baseTx := dao.CasbinRuleEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(updateOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	fn(tx)
	_, err := tx.Apply().UpdateSimple(updateOpts.Columns...)
	if err == nil {
		// 条件更新无法预知影响哪些 ID，全表缓存清掉最安全
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) UpdateByWrapperTx(ctx context.Context, daoTx *dao.Query, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), opts ...gormplus.UpdateOption) error {
	if fn == nil {
		return errors.New("更新条件不能为空")
	}
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	baseTx := daoTx.CasbinRuleEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(updateOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	fn(tx)
	_, err := tx.Apply().UpdateSimple(updateOpts.Columns...)
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultCasbinRuleRepository) FindList(ctx context.Context, query ...gormplus.QueryOption) ([]*model.CasbinRuleEntity, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.FindList", nil,
		func() ([]*model.CasbinRuleEntity, error) {
			return r.buildTx(ctx, query).Find()
		},
	)
}

func (r *defaultCasbinRuleRepository) FindListByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) ([]*model.CasbinRuleEntity, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.FindListByWrapper", nil,
		func() ([]*model.CasbinRuleEntity, error) {
			return r.buildWrapperTx(ctx, fn, query).Find()
		},
	)
}

func (r *defaultCasbinRuleRepository) FindPage(ctx context.Context, pageNumber int64, pageSize int64, query ...gormplus.QueryOption) (list []*model.CasbinRuleEntity, total int64, err error) {
	offset := int((pageNumber - 1) * pageSize)
	limit := int(pageSize)
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecutePage(opt, "casbin_rule.FindPage",
		gormplus.BuildArgs("page", pageNumber, "size", pageSize),
		func() ([]*model.CasbinRuleEntity, int64, error) {
			return r.buildTx(ctx, query).FindByPage(offset, limit)
		},
	)
}

func (r *defaultCasbinRuleRepository) FindPageByWrapper(ctx context.Context, pageNumber int64, pageSize int64, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (list []*model.CasbinRuleEntity, total int64, err error) {
	offset := int((pageNumber - 1) * pageSize)
	limit := int(pageSize)
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecutePage(opt, "casbin_rule.FindPageByWrapper",
		gormplus.BuildArgs("page", pageNumber, "size", pageSize),
		func() ([]*model.CasbinRuleEntity, int64, error) {
			return r.buildWrapperTx(ctx, fn, query).FindByPage(offset, limit)
		},
	)
}

func (r *defaultCasbinRuleRepository) FindById(ctx context.Context, casbinRuleId int64, query ...gormplus.QueryOption) (*model.CasbinRuleEntity, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.FindById",
		gormplus.BuildArgs("id", casbinRuleId),
		func() (*model.CasbinRuleEntity, error) {
			tx := dao.CasbinRuleEntity.WithContext(ctx)
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			return tx.Where(
				dao.CasbinRuleEntity.ID.Eq(casbinRuleId),
			).First()
		},
	)
}
func (r *defaultCasbinRuleRepository) FindByIdList(ctx context.Context, casbinRuleIds []int64, query ...gormplus.QueryOption) ([]*model.CasbinRuleEntity, error) {
	if len(casbinRuleIds) == 0 {
		return []*model.CasbinRuleEntity{}, nil
	}
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.FindByIdList",
		gormplus.BuildArgs("ids", casbinRuleIds),
		func() ([]*model.CasbinRuleEntity, error) {
			tx := dao.CasbinRuleEntity.WithContext(ctx).Where(dao.CasbinRuleEntity.ID.In(casbinRuleIds...))
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			if len(opt.Cond) > 0 {
				tx = tx.Where(opt.Cond...)
			}
			if len(opt.Select) > 0 {
				tx = tx.Select(opt.Select...)
			}
			if len(opt.OmitFields) > 0 {
				tx = tx.Omit(opt.OmitFields...)
			}
			if len(opt.Order) > 0 {
				tx = tx.Order(opt.Order...)
			}
			if opt.Limit != nil {
				tx = tx.Limit(*opt.Limit)
			}
			return tx.Find()
		},
	)
}

func (r *defaultCasbinRuleRepository) FindOne(ctx context.Context, query ...gormplus.QueryOption) (*model.CasbinRuleEntity, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.FindOne", nil,
		func() (*model.CasbinRuleEntity, error) {
			return r.buildTx(ctx, query).First()
		},
	)
}

func (r *defaultCasbinRuleRepository) FindOneWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (*model.CasbinRuleEntity, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.FindOneWrapper", nil,
		func() (*model.CasbinRuleEntity, error) {
			return r.buildWrapperTx(ctx, fn, query).First()
		},
	)
}

func (r *defaultCasbinRuleRepository) Exists(ctx context.Context, query ...gormplus.QueryOption) (bool, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.Exists", nil,
		func() (bool, error) {
			tx := dao.CasbinRuleEntity.WithContext(ctx)
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			if len(opt.Cond) > 0 {
				tx = tx.Where(opt.Cond...)
			}
			cnt, err := tx.Count()
			if err != nil {
				return false, err
			}
			return cnt > 0, nil
		},
	)
}

func (r *defaultCasbinRuleRepository) ExistsByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (bool, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.ExistsByWrapper", nil,
		func() (bool, error) {
			baseTx := dao.CasbinRuleEntity.WithContext(ctx)
			if opt.Unscoped {
				baseTx = baseTx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				baseTx = baseTx.Clauses(opt.Clauses...)
			}
			tx := gormplus.GenWrap(baseTx)
			if opt.Unscoped {
				tx.WithDeleted()
			}
			if fn != nil {
				fn(tx)
			}
			cnt, err := tx.Apply().Count()
			if err != nil {
				return false, err
			}
			return cnt > 0, nil
		},
	)
}

func (r *defaultCasbinRuleRepository) Count(ctx context.Context, query ...gormplus.QueryOption) (int64, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.Count", nil,
		func() (int64, error) {
			tx := dao.CasbinRuleEntity.WithContext(ctx)
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			if len(opt.Cond) > 0 {
				tx = tx.Where(opt.Cond...)
			}
			return tx.Count()
		},
	)
}

func (r *defaultCasbinRuleRepository) CountByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ICasbinRuleEntityDo]), query ...gormplus.QueryOption) (int64, error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "casbin_rule.CountByWrapper", nil,
		func() (int64, error) {
			baseTx := dao.CasbinRuleEntity.WithContext(ctx)
			if opt.Unscoped {
				baseTx = baseTx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				baseTx = baseTx.Clauses(opt.Clauses...)
			}
			tx := gormplus.GenWrap(baseTx)
			if opt.Unscoped {
				tx.WithDeleted()
			}
			if fn != nil {
				fn(tx)
			}
			return tx.Apply().Count()
		},
	)
}

func newDefaultCasbinRuleRepository() *defaultCasbinRuleRepository {
	return &defaultCasbinRuleRepository{}
}
