// Code generated by gorm-plus generator. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"github.com/kuangshp/gorm-plus"
	"gorm.io/gen"
	"gin-admin-api/internal/dal/dao"
	"gin-admin-api/internal/dal/model"
)

type defaultSysRoleCustomDeptRepository struct {
}

type iDefaultSysRoleCustomDeptRepository interface {
	// Create 创建记录（自动失效 FindList / FindPage / Count / Exists 前缀缓存）
	Create(ctx context.Context, m *model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error
	CreateTx(ctx context.Context, tx *dao.Query, m *model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error
	// CreateBatch 批量创建（自动失效 FindList / FindPage / Count / Exists 前缀缓存）
	CreateBatch(ctx context.Context, m []*model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error
	CreateBatchTx(ctx context.Context, tx *dao.Query, m []*model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error
	// DeleteById 根据ID删除（默认软删除；传 gormplus.Delete().WithPhysicalDelete().Build() 时物理删除。自动失效该 ID 的 FindById，以及 FindList/FindPage/Count/Exists 前缀缓存）
	DeleteById(ctx context.Context, sysRoleCustomDeptId int64, opts ...gormplus.DeleteOption) error
	DeleteByIdTx(ctx context.Context, tx *dao.Query, sysRoleCustomDeptId int64, opts ...gormplus.DeleteOption) error
	// DeleteByIdList 根据ID列表批量删除（自动失效每个 ID 的 FindById，以及 FindList/FindPage/Count/Exists 前缀缓存）
	DeleteByIdList(ctx context.Context, sysRoleCustomDeptIds []int64, opts ...gormplus.DeleteOption) error
	DeleteByIdListTx(ctx context.Context, tx *dao.Query, sysRoleCustomDeptIds []int64, opts ...gormplus.DeleteOption) error
	// DeleteByCondition 根据原生条件删除（默认软删除；传 gormplus.Delete().WithPhysicalDelete().Build() 时物理删除。自动按表名前缀失效全部缓存，因无法预知影响的 ID）
	DeleteByCondition(ctx context.Context, cond ...gen.Condition) error
	DeleteByConditionTx(ctx context.Context, tx *dao.Query, cond ...gen.Condition) error
	// DeleteByWrapper 根据wrapper条件删除（默认软删除；传 gormplus.Delete().WithPhysicalDelete().Build() 时物理删除。自动按表名前缀失效全部缓存，因无法预知影响的 ID）
	DeleteByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.DeleteOption) error
	DeleteByWrapperTx(ctx context.Context, tx *dao.Query, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.DeleteOption) error
	// UpdateById 根据ID更新指定字段（自动失效该 ID 的 FindById，以及 FindList/FindPage 前缀缓存）
	UpdateById(ctx context.Context, sysRoleCustomDeptId int64, opts ...gormplus.UpdateOption) error
	UpdateByIdTx(ctx context.Context, tx *dao.Query, sysRoleCustomDeptId int64, opts ...gormplus.UpdateOption) error
	// UpdateMapById 根据ID更新Map数据（自动失效该 ID 的 FindById，以及 FindList/FindPage 前缀缓存）
	UpdateMapById(ctx context.Context, sysRoleCustomDeptId int64, data map[string]any) error
	UpdateMapByIdTx(ctx context.Context, tx *dao.Query, sysRoleCustomDeptId int64, data map[string]any) error
	// UpdateByWrapper 根据wrapper条件更新（自动按表名前缀失效全部缓存，因无法预知影响的 ID）
	UpdateByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.UpdateOption) error
	UpdateByWrapperTx(ctx context.Context, tx *dao.Query, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.UpdateOption) error
	// FindList 根据原生条件获取列表
	FindList(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error)
	// FindListByWrapper 根据wrapper条件获取列表
	FindListByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error)
	// FindPage 根据原生条件分页查询
	FindPage(ctx context.Context, pageNumber int64, pageSize int64, query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, sysRoleCustomDeptTotal int64, err error)
	// FindPageByWrapper 根据wrapper条件分页查询
	FindPageByWrapper(ctx context.Context, pageNumber int64, pageSize int64, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, sysRoleCustomDeptTotal int64, err error)
	// FindById 根据ID获取详情（支持 query.WithCache / query.WithSingleFlight）
	FindById(ctx context.Context, sysRoleCustomDeptId int64, query ...gormplus.QueryOption) (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error)
	// FindByIdList 根据ID列表获取（支持 query.WithCache / query.WithSingleFlight）
	FindByIdList(ctx context.Context, sysRoleCustomDeptIds []int64, query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error)
	// FindOne 根据原生条件获取单条
	FindOne(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error)
	// FindOneWrapper 根据wrapper条件获取单条
	FindOneWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error)
	// Exists 根据原生条件判断是否存在（支持 query.WithCache / query.WithSingleFlight）
	Exists(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDeptExists bool, err error)
	// ExistsByWrapper 根据wrapper条件判断是否存在（支持 query.WithCache / query.WithSingleFlight）
	ExistsByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptExists bool, err error)
	// Count 根据原生条件统计数量（支持 query.WithCache / query.WithSingleFlight）
	Count(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDeptCount int64, err error)
	// CountByWrapper 根据wrapper条件统计数量（支持 query.WithCache / query.WithSingleFlight）
	CountByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptCount int64, err error)
}

// ==================== 缓存失效辅助方法 ====================
//
// 缓存策略总览（统一以 "sys_role_custom_dept.方法名" 为 fnName）：
//
//	写操作              失效范围
//	──────────         ─────────────────────────────────────────────────────────
//	Create / Update     invalidateWriteCaches：清 List/Page/Count/Exists 全部前缀
//	  / Delete (by id)  + 单条 FindById（精确）
//	条件 Update/Delete  invalidateAllTableCaches：整张表（按表名前缀失效）
//
// 设计说明：
//   - 三类写操作的 List/Aggregate 失效范围相同，合并成一个函数，避免 Redis 多次 SCAN
//   - 用 SFInvalidatePrefixes 批量接口：Redis 场景下从 11 次 SCAN 降为 1 次 pipeline
//   - 关于 Update 清 Count/Exists：软删除场景（deleted_at 字段更新）走的就是 Update，
//     若不清 Count/Exists 会导致"删了但 Count 还是旧值"，所以宁可保守失效

// invalidateWriteCaches 失效所有受写操作影响的缓存（List / Page / Count / Exists + 衍生方法）。
// 用于 Create / Update / Delete 三类已知 ID 的写操作。
func (r *defaultSysRoleCustomDeptRepository) invalidateWriteCaches() {
	gormplus.SFInvalidatePrefixes([]string{
		"sys_role_custom_dept.FindList",
		"sys_role_custom_dept.FindListByWrapper",
		"sys_role_custom_dept.FindPage",
		"sys_role_custom_dept.FindPageByWrapper",
		"sys_role_custom_dept.FindByIdList",
		"sys_role_custom_dept.FindOne",
		"sys_role_custom_dept.FindOneWrapper",
		"sys_role_custom_dept.Count",
		"sys_role_custom_dept.CountByWrapper",
		"sys_role_custom_dept.Exists",
		"sys_role_custom_dept.ExistsByWrapper",
	})
}

// invalidateAllTableCaches 失效整张表所有缓存（用于条件 Update / Delete，无法预知影响的 ID）。
// 包括 FindById 在内的所有方法都会被清掉。
func (r *defaultSysRoleCustomDeptRepository) invalidateAllTableCaches() {
	gormplus.SFInvalidatePrefix("sys_role_custom_dept.")
}

// ==================== 公共构建方法 ====================

func (r *defaultSysRoleCustomDeptRepository) buildTx(ctx context.Context, query []gormplus.QueryOption) dao.ISysRoleCustomDeptEntityDo {
	if len(query) == 0 {
		return dao.SysRoleCustomDeptEntity.WithContext(ctx).Order(dao.SysRoleCustomDeptEntity.ID.Desc())
	}
	q := gormplus.MergeQueryOptions(query...)
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if q.Unscoped {
		tx = tx.Unscoped()
	}
	if len(q.Clauses) > 0 {
		tx = tx.Clauses(q.Clauses...)
	}
	if len(q.Cond) > 0 {
		tx = tx.Where(q.Cond...)
	}
	if len(q.Select) > 0 {
		tx = tx.Select(q.Select...)
	}
	if len(q.OmitFields) > 0 {
		tx = tx.Omit(q.OmitFields...)
	}
	if len(q.Order) > 0 {
		tx = tx.Order(q.Order...)
	} else {
		tx = tx.Order(dao.SysRoleCustomDeptEntity.ID.Desc())
	}
	if q.Limit != nil {
		tx = tx.Limit(*q.Limit)
	}
	return tx
}

func (r *defaultSysRoleCustomDeptRepository) buildWrapperTx(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query []gormplus.QueryOption) dao.ISysRoleCustomDeptEntityDo {
	q := gormplus.MergeQueryOptions(query...)
	baseTx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if q.Unscoped {
		baseTx = baseTx.Unscoped()
	}
	if len(q.Clauses) > 0 {
		baseTx = baseTx.Clauses(q.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if q.Unscoped {
		tx.WithDeleted()
	}

    if fn != nil {
        fn(tx)
    }
    entityDo := tx.Apply()
    if len(query) > 0 {
        if len(q.Cond) > 0 {
            entityDo = entityDo.Where(q.Cond...)
        }
        if len(q.Select) > 0 {
            entityDo = entityDo.Select(q.Select...)
        }
        if len(q.OmitFields) > 0 {
            entityDo = entityDo.Omit(q.OmitFields...)
        }
        if len(q.Order) > 0 {
            entityDo = entityDo.Order(q.Order...)
        } else {
            entityDo = entityDo.Order(dao.SysRoleCustomDeptEntity.ID.Desc())
        }
        if q.Limit != nil {
            entityDo = entityDo.Limit(*q.Limit)
        }
	}
	return entityDo
}

// SysRoleCustomDeptJoinQueryBuilder 构建SysRoleCustomDept连表查询基础语句。
type SysRoleCustomDeptJoinQueryBuilder func(ctx context.Context) dao.ISysRoleCustomDeptEntityDo

// newDefaultSysRoleCustomDeptJoinQuery 创建SysRoleCustomDept默认连表查询基础语句。
func newDefaultSysRoleCustomDeptJoinQuery(ctx context.Context) dao.ISysRoleCustomDeptEntityDo {
	return dao.SysRoleCustomDeptEntity.WithContext(ctx)
}

// buildSysRoleCustomDeptJoinTx 构建SysRoleCustomDept连表查询语句。
func buildSysRoleCustomDeptJoinTx(ctx context.Context, build SysRoleCustomDeptJoinQueryBuilder, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query []gormplus.QueryOption) dao.ISysRoleCustomDeptEntityDo {
	q := gormplus.MergeQueryOptions(query...)
	if build == nil {
		build = newDefaultSysRoleCustomDeptJoinQuery
	}
	baseTx := build(ctx)
	if q.Unscoped {
		baseTx = baseTx.Unscoped()
	}
	if len(q.Clauses) > 0 {
		baseTx = baseTx.Clauses(q.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if q.Unscoped {
		tx.WithDeleted()
	}
	if fn != nil {
		fn(tx)
	}
	entityDo := tx.Apply()
	if len(q.Cond) > 0 {
		entityDo = entityDo.Where(q.Cond...)
	}
	if len(q.Select) > 0 {
		entityDo = entityDo.Select(q.Select...)
	}
	if len(q.OmitFields) > 0 {
		entityDo = entityDo.Omit(q.OmitFields...)
	}
	if len(q.Order) > 0 {
		entityDo = entityDo.Order(q.Order...)
	}
	if q.Limit != nil {
		entityDo = entityDo.Limit(*q.Limit)
	}
	return entityDo
}

// FindSysRoleCustomDeptJoinList 查询SysRoleCustomDept连表列表，T 可以是调用方自定义的行结构体。
func FindSysRoleCustomDeptJoinList[T any](ctx context.Context, build SysRoleCustomDeptJoinQueryBuilder, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (rows []T, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindJoinList", nil,
		func() (rows []T, err error) {
			rows = make([]T, 0)
			err = buildSysRoleCustomDeptJoinTx(ctx, build, fn, query).Scan(&rows)
			return rows, err
		},
	)
}

// FindSysRoleCustomDeptJoinPage 分页查询SysRoleCustomDept连表列表，T 可以是调用方自定义的行结构体。
func FindSysRoleCustomDeptJoinPage[T any](ctx context.Context, pageNumber int64, pageSize int64, build SysRoleCustomDeptJoinQueryBuilder, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (rows []T, total int64, err error) {
	offset, limit := gormplus.DbPage(pageNumber, pageSize)
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecutePage(opt, "sys_role_custom_dept.FindJoinPage",
		gormplus.BuildArgs("page", pageNumber, "size", pageSize),
		func() (rows []T, total int64, err error) {
			rows = make([]T, 0)
			total, err = buildSysRoleCustomDeptJoinTx(ctx, build, fn, query).ScanByPage(&rows, offset, limit)
			return rows, total, err
		},
	)
}

// FindSysRoleCustomDeptJoinOne 查询SysRoleCustomDept连表单条数据，T 可以是调用方自定义的行结构体。
func FindSysRoleCustomDeptJoinOne[T any](ctx context.Context, build SysRoleCustomDeptJoinQueryBuilder, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (row T, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindJoinOne", nil,
		func() (row T, err error) {
			err = buildSysRoleCustomDeptJoinTx(ctx, build, fn, query).Limit(1).Scan(&row)
			return row, err
		},
	)
}

// ==================== 实现 ====================

func (r *defaultSysRoleCustomDeptRepository) Create(ctx context.Context, m *model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error {
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.Create(m)
	if err == nil {
		// 新增：列表/分页 + 数量/存在性缓存全部失效
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) CreateTx(ctx context.Context, daoTx *dao.Query, m *model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error {
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.Create(m)
	if err == nil {
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) CreateBatch(ctx context.Context, m []*model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error {
	if len(m) == 0 {
		return nil
	}
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.CreateInBatches(m, len(m))
	if err == nil {
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) CreateBatchTx(ctx context.Context, daoTx *dao.Query, m []*model.SysRoleCustomDeptEntity, opts ...gormplus.CreateOption) error {
	if len(m) == 0 {
		return nil
	}
	createOpts := gormplus.ResolveCreateOptions(opts)
	tx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(createOpts.OmitFields) > 0 {
		tx = tx.Omit(createOpts.OmitFields...)
	}
	if len(createOpts.Clauses) > 0 {
		tx = tx.Clauses(createOpts.Clauses...)
	}
	err := tx.CreateInBatches(m, len(m))
	if err == nil {
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteById(ctx context.Context, sysRoleCustomDeptId int64, opts ...gormplus.DeleteOption) error {
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
	).Delete()
	if err == nil {
		// 删除：单条精确失效 + 列表/分页前缀失效 + 数量/存在性前缀失效
		gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", sysRoleCustomDeptId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteByIdTx(ctx context.Context, daoTx *dao.Query, sysRoleCustomDeptId int64, opts ...gormplus.DeleteOption) error {
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
	).Delete()
	if err == nil {
		gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", sysRoleCustomDeptId))
		r.invalidateWriteCaches()
	}
	return err
}
func (r *defaultSysRoleCustomDeptRepository) DeleteByIdList(ctx context.Context, sysRoleCustomDeptIds []int64, opts ...gormplus.DeleteOption) error {
	if len(sysRoleCustomDeptIds) == 0 {
		return nil
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(dao.SysRoleCustomDeptEntity.ID.In(sysRoleCustomDeptIds...)).Delete()
	if err == nil {
		for _, id := range sysRoleCustomDeptIds {
			gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", id))
		}
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteByIdListTx(ctx context.Context, daoTx *dao.Query, sysRoleCustomDeptIds []int64, opts ...gormplus.DeleteOption) error {
	if len(sysRoleCustomDeptIds) == 0 {
		return nil
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	tx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(dao.SysRoleCustomDeptEntity.ID.In(sysRoleCustomDeptIds...)).Delete()
	if err == nil {
		for _, id := range sysRoleCustomDeptIds {
			gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", id))
		}
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteByCondition(ctx context.Context, cond ...gen.Condition) error {
	cond, deleteOpts := gormplus.SplitDeleteConditions(cond)
	if len(cond) == 0 {
		return errors.New("删除条件不能为空")
	}
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(cond...).Delete()
	if err == nil {
		// 条件删除无法预知影响哪些 ID，全表缓存清掉最安全
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteByConditionTx(ctx context.Context, daoTx *dao.Query, cond ...gen.Condition) error {
	cond, deleteOpts := gormplus.SplitDeleteConditions(cond)
	if len(cond) == 0 {
		return errors.New("删除条件不能为空")
	}
	tx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		tx = tx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		tx = tx.Clauses(deleteOpts.Clauses...)
	}
	_, err := tx.Where(cond...).Delete()
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.DeleteOption) error {
	if fn == nil {
		return errors.New("删除条件不能为空")
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	baseTx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		baseTx = baseTx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(deleteOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if deleteOpts.Physical {
		tx.WithDeleted()
	}
	fn(tx)
	_, err := tx.Apply().Delete()
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) DeleteByWrapperTx(ctx context.Context, daoTx *dao.Query, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.DeleteOption) error {
	if fn == nil {
		return errors.New("删除条件不能为空")
	}
	deleteOpts := gormplus.ResolveDeleteOptions(opts)
	baseTx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if deleteOpts.Physical {
		baseTx = baseTx.Unscoped()
	}
	if len(deleteOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(deleteOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	if deleteOpts.Physical {
		tx.WithDeleted()
	}
	fn(tx)
	_, err := tx.Apply().Delete()
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) UpdateById(ctx context.Context, sysRoleCustomDeptId int64, opts ...gormplus.UpdateOption) error {
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		tx = tx.Clauses(updateOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
	).UpdateSimple(updateOpts.Columns...)
	if err == nil {
		// 修改：单条精确失效 + 列表/分页前缀失效（数量/存在性一般不受影响）
		gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", sysRoleCustomDeptId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) UpdateByIdTx(ctx context.Context, daoTx *dao.Query, sysRoleCustomDeptId int64, opts ...gormplus.UpdateOption) error {
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	tx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		tx = tx.Clauses(updateOpts.Clauses...)
	}
	_, err := tx.Where(
		dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
	).UpdateSimple(updateOpts.Columns...)
	if err == nil {
		gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", sysRoleCustomDeptId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) UpdateMapById(ctx context.Context, sysRoleCustomDeptId int64, data map[string]any) error {
	if len(data) == 0 {
		return nil
	}
	_, err := dao.SysRoleCustomDeptEntity.WithContext(ctx).
		Where(
			dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
		).
		Updates(data)
	if err == nil {
		gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", sysRoleCustomDeptId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) UpdateMapByIdTx(ctx context.Context, daoTx *dao.Query, sysRoleCustomDeptId int64, data map[string]any) error {
	if len(data) == 0 {
		return nil
	}
	_, err := daoTx.SysRoleCustomDeptEntity.WithContext(ctx).
		Where(
			dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
		).
		Updates(data)
	if err == nil {
		gormplus.SFInvalidate("sys_role_custom_dept.FindById", gormplus.BuildArgs("id", sysRoleCustomDeptId))
		r.invalidateWriteCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) UpdateByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.UpdateOption) error {
	if fn == nil {
		return errors.New("更新条件不能为空")
	}
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	baseTx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(updateOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	fn(tx)
	_, err := tx.Apply().UpdateSimple(updateOpts.Columns...)
	if err == nil {
		// 条件更新无法预知影响哪些 ID，全表缓存清掉最安全
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) UpdateByWrapperTx(ctx context.Context, daoTx *dao.Query, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), opts ...gormplus.UpdateOption) error {
	if fn == nil {
		return errors.New("更新条件不能为空")
	}
	updateOpts := gormplus.ResolveUpdateOptions(opts)
	if len(updateOpts.Columns) == 0 {
		return nil
	}
	baseTx := daoTx.SysRoleCustomDeptEntity.WithContext(ctx)
	if len(updateOpts.Clauses) > 0 {
		baseTx = baseTx.Clauses(updateOpts.Clauses...)
	}
	tx := gormplus.GenWrap(baseTx)
	fn(tx)
	_, err := tx.Apply().UpdateSimple(updateOpts.Columns...)
	if err == nil {
		r.invalidateAllTableCaches()
	}
	return err
}

func (r *defaultSysRoleCustomDeptRepository) FindList(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindList", nil,
		func() (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error) {
			return r.buildTx(ctx, query).Find()
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) FindListByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindListByWrapper", nil,
		func() (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error) {
			return r.buildWrapperTx(ctx, fn, query).Find()
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) FindPage(ctx context.Context, pageNumber int64, pageSize int64, query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, sysRoleCustomDeptTotal int64, err error) {
	offset := int((pageNumber - 1) * pageSize)
	limit := int(pageSize)
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecutePage(opt, "sys_role_custom_dept.FindPage",
		gormplus.BuildArgs("page", pageNumber, "size", pageSize),
		func() (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, total int64, err error) {
			return r.buildTx(ctx, query).FindByPage(offset, limit)
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) FindPageByWrapper(ctx context.Context, pageNumber int64, pageSize int64, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, sysRoleCustomDeptTotal int64, err error) {
	offset := int((pageNumber - 1) * pageSize)
	limit := int(pageSize)
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecutePage(opt, "sys_role_custom_dept.FindPageByWrapper",
		gormplus.BuildArgs("page", pageNumber, "size", pageSize),
		func() (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, total int64, err error) {
			return r.buildWrapperTx(ctx, fn, query).FindByPage(offset, limit)
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) FindById(ctx context.Context, sysRoleCustomDeptId int64, query ...gormplus.QueryOption) (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindById",
		gormplus.BuildArgs("id", sysRoleCustomDeptId),
		func() (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error) {
			tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			return tx.Where(
				dao.SysRoleCustomDeptEntity.ID.Eq(sysRoleCustomDeptId),
			).First()
		},
	)
}
func (r *defaultSysRoleCustomDeptRepository) FindByIdList(ctx context.Context, sysRoleCustomDeptIds []int64, query ...gormplus.QueryOption) (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error) {
	if len(sysRoleCustomDeptIds) == 0 {
		return []*model.SysRoleCustomDeptEntity{}, nil
	}
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindByIdList",
		gormplus.BuildArgs("ids", sysRoleCustomDeptIds),
		func() (sysRoleCustomDeptList []*model.SysRoleCustomDeptEntity, err error) {
			tx := dao.SysRoleCustomDeptEntity.WithContext(ctx).Where(dao.SysRoleCustomDeptEntity.ID.In(sysRoleCustomDeptIds...))
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			if len(opt.Cond) > 0 {
				tx = tx.Where(opt.Cond...)
			}
			if len(opt.Select) > 0 {
				tx = tx.Select(opt.Select...)
			}
			if len(opt.OmitFields) > 0 {
				tx = tx.Omit(opt.OmitFields...)
			}
			if len(opt.Order) > 0 {
				tx = tx.Order(opt.Order...)
			}
			if opt.Limit != nil {
				tx = tx.Limit(*opt.Limit)
			}
			return tx.Find()
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) FindOne(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindOne", nil,
		func() (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error) {
			return r.buildTx(ctx, query).First()
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) FindOneWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.FindOneWrapper", nil,
		func() (sysRoleCustomDept *model.SysRoleCustomDeptEntity, err error) {
			return r.buildWrapperTx(ctx, fn, query).First()
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) Exists(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDeptExists bool, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.Exists", nil,
		func() (sysRoleCustomDeptExists bool, err error) {
			tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			if len(opt.Cond) > 0 {
				tx = tx.Where(opt.Cond...)
			}
			cnt, err := tx.Count()
			if err != nil {
				return false, err
			}
			return cnt > 0, nil
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) ExistsByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptExists bool, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.ExistsByWrapper", nil,
		func() (sysRoleCustomDeptExists bool, err error) {
			baseTx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
			if opt.Unscoped {
				baseTx = baseTx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				baseTx = baseTx.Clauses(opt.Clauses...)
			}
			tx := gormplus.GenWrap(baseTx)
			if opt.Unscoped {
				tx.WithDeleted()
			}
			if fn != nil {
				fn(tx)
			}
			cnt, err := tx.Apply().Count()
			if err != nil {
				return false, err
			}
			return cnt > 0, nil
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) Count(ctx context.Context, query ...gormplus.QueryOption) (sysRoleCustomDeptCount int64, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.Count", nil,
		func() (sysRoleCustomDeptCount int64, err error) {
			tx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
			if opt.Unscoped {
				tx = tx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				tx = tx.Clauses(opt.Clauses...)
			}
			if len(opt.Cond) > 0 {
				tx = tx.Where(opt.Cond...)
			}
			return tx.Count()
		},
	)
}

func (r *defaultSysRoleCustomDeptRepository) CountByWrapper(ctx context.Context, fn func(gormplus.IGenWrapper[dao.ISysRoleCustomDeptEntityDo]), query ...gormplus.QueryOption) (sysRoleCustomDeptCount int64, err error) {
	opt := gormplus.MergeQueryOptions(query...)
	return gormplus.ExecuteQuery(opt, "sys_role_custom_dept.CountByWrapper", nil,
		func() (sysRoleCustomDeptCount int64, err error) {
			baseTx := dao.SysRoleCustomDeptEntity.WithContext(ctx)
			if opt.Unscoped {
				baseTx = baseTx.Unscoped()
			}
			if len(opt.Clauses) > 0 {
				baseTx = baseTx.Clauses(opt.Clauses...)
			}
			tx := gormplus.GenWrap(baseTx)
			if opt.Unscoped {
				tx.WithDeleted()
			}
			if fn != nil {
				fn(tx)
			}
			return tx.Apply().Count()
		},
	)
}

func newDefaultSysRoleCustomDeptRepository() *defaultSysRoleCustomDeptRepository {
	return &defaultSysRoleCustomDeptRepository{}
}
