// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/account/list": {
            "get": {
                "description": "根据查询条件获取账号列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "获取账号列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录账号",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "账号列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.SysAccountVO"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/modify/{id}": {
            "put": {
                "description": "根据账号 ID 修改账号基础信息和角色关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "修改账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改账号参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModifySysAccountDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/modifyCurrentPassword": {
            "post": {
                "description": "修改当前登录账号密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "修改当前账号密码",
                "parameters": [
                    {
                        "description": "修改当前账号密码参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ModifyCurrentPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改当前账号密码成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/page": {
            "post": {
                "description": "根据查询条件分页获取账号列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "分页获取账号",
                "parameters": [
                    {
                        "description": "分页查询参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetSysAccountPageDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "统一响应，code=0 时 result 为账号分页数据，code=1 时 result 为 null",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vo.SysAccountVO"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/register": {
            "post": {
                "description": "创建后台账号，并分配角色关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "创建账号",
                "parameters": [
                    {
                        "description": "创建账号参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateSysAccountDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/resetPassword/{id}": {
            "post": {
                "description": "根据账号 ID 重置账号密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "重置账号密码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "重置密码参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "重置密码成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/account/{id}": {
            "get": {
                "description": "根据账号 ID 获取账号详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "获取账号详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "统一响应，code=0 时 result 为 vo.SysAccountVO，code=1 时 result 为 null",
                        "schema": {
                            "$ref": "#/definitions/vo.SysAccountVO"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据账号 ID 删除账号，并清理账号角色关系",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账号中心"
                ],
                "summary": "删除账号",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "账号ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/auth/captcha": {
            "get": {
                "description": "生成图形验证码，返回验证码图片 Base64、验证码 ID 和验证码值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证中心"
                ],
                "summary": "获取图形验证码图片",
                "responses": {
                    "200": {
                        "description": "统一响应，code=0 时 result 为 vo.GetCaptchaVO，code=1 时 result 为 null",
                        "schema": {
                            "$ref": "#/definitions/vo.GetCaptchaVO"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/auth/captcha/verify": {
            "post": {
                "description": "根据验证码 ID 和验证码值校验图形验证码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证中心"
                ],
                "summary": "验证图形验证码",
                "parameters": [
                    {
                        "description": "验证码参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyCaptchaDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "验证码成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/auth/login": {
            "post": {
                "description": "使用账号、邮箱或手机号登录，登录成功后返回账号信息和 token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证中心"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AccountLoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "统一响应，code=0 时 result 为 vo.AccountLoginVO，code=1 时 result 为 null",
                        "schema": {
                            "$ref": "#/definitions/vo.AccountLoginVO"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/auth/logout": {
            "post": {
                "description": "删除当前登录用户的 token 缓存",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "认证中心"
                ],
                "summary": "用户退出登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录 token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "退出登录成功",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AccountLoginDTO": {
            "type": "object",
            "required": [
                "captchaId",
                "captchaValue",
                "password",
                "username"
            ],
            "properties": {
                "captchaId": {
                    "description": "图形验证码id",
                    "type": "string"
                },
                "captchaValue": {
                    "description": "图形验证码",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string"
                },
                "username": {
                    "description": "登录帐号",
                    "type": "string"
                }
            }
        },
        "dto.CreateSysAccountDTO": {
            "type": "object",
            "required": [
                "confirmPassword",
                "password",
                "roleIdList",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "confirmPassword": {
                    "description": "确定密码",
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "roleIdList": {
                    "description": "授权的角色id",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "username": {
                    "description": "登录帐号",
                    "type": "string"
                }
            }
        },
        "dto.GetSysAccountPageDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "pageNumber": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "status": {
                    "description": "状态1是正常,2是禁用",
                    "type": "integer"
                },
                "username": {
                    "description": "登录帐号",
                    "type": "string"
                }
            }
        },
        "dto.ModifyCurrentPasswordDTO": {
            "type": "object",
            "required": [
                "confirmPassword",
                "newPassword",
                "password"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "newPassword": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                }
            }
        },
        "dto.ModifySysAccountDTO": {
            "type": "object",
            "required": [
                "id",
                "roleIdList",
                "status",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer",
                    "minimum": 1
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "roleIdList": {
                    "description": "授权的角色id",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "description": "状态1是正常,2是禁用",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "username": {
                    "description": "登录帐号",
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordDTO": {
            "type": "object",
            "required": [
                "confirmPassword",
                "id",
                "password"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                }
            }
        },
        "dto.VerifyCaptchaDTO": {
            "type": "object",
            "required": [
                "captchaId",
                "captchaValue"
            ],
            "properties": {
                "captchaId": {
                    "description": "图形验证码id",
                    "type": "string"
                },
                "captchaValue": {
                    "description": "图形验证码",
                    "type": "string"
                }
            }
        },
        "vo.AccountLoginVO": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "isAdmin": {
                    "description": "1是超级管理员，2是普通管理员",
                    "type": "integer"
                },
                "lastLoginDate": {
                    "description": "最后一次登录时间",
                    "type": "integer"
                },
                "lastLoginIp": {
                    "description": "最后一次登录ip",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "username": {
                    "description": "登录帐号",
                    "type": "string"
                }
            }
        },
        "vo.GetCaptchaVO": {
            "type": "object",
            "properties": {
                "base64": {
                    "description": "base64",
                    "type": "string"
                },
                "captchaId": {
                    "description": "唯一码",
                    "type": "string"
                },
                "code": {
                    "description": "验证码",
                    "type": "string"
                }
            }
        },
        "vo.SysAccountVO": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人",
                    "type": "integer"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "id": {
                    "description": "主键id",
                    "type": "integer"
                },
                "isAdmin": {
                    "description": "1是超级管理员，2是普通管理员",
                    "type": "integer"
                },
                "lastLoginDate": {
                    "description": "最后一次登录时间",
                    "type": "integer"
                },
                "lastLoginIP": {
                    "description": "最后一次登录ip",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string"
                },
                "status": {
                    "description": "状态1是正常,2是禁用",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人",
                    "type": "integer"
                },
                "username": {
                    "description": "登录帐号",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "gin-admin-api",
	Description:      "gin-admin-api 后台管理接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
